### ISSUE TITLE
Nearly all of my TV Shows won't show up in Plex

### ISSUE THREAD

**Issue by ashtonlance** [Cloudbox/Cloudbox#113]
I can see all my files in the /mtn/unionfs directory. However, when adding the data/TV folder as my TV Shows library -- only one season of three different shows appears. I've used all the same data with another Plex setup and never had any problems. Any ideas? How do I go about diagnosing?

**Comment by ashtonlance** [comment]
Here's my scanner log
[Plex Media Scanner.log](https://github.com/Cloudbox/Cloudbox/files/1808583/Plex.Media.Scanner.log)

**Comment by desimaniac** [comment]
You need to fix your paths structure. See Plex recommendations on naming. 

Basically, it should be /Media/TV/Show Name/ Season X (or XX)/show name - SXXEXX - (episode name if you want).Ext

This is what you have:
data/TV/Alone.Season.1.Complete.incl.Extra.HDTV.x264"

**Comment by ashtonlance** [comment]
Thanks for the help!

I've tried renaming a couple of my shows and still no dice. The scanner shows that it's getting to the parent directory (the show) and error-ing out -- it's not even looking inside. I'll attach my last scanner log.

Seinfeld, The Young Pope and Planet Earth II are the only ones appearing in plex.

[Plex Media Scanner.log](https://github.com/Cloudbox/Cloudbox/files/1811157/Plex.Media.Scanner.log)

**Comment by desimaniac** [comment]
You should join our Discord chat server (link is on main GitHub page). It's a better place to troubleshoot and there are other users there as well.
