### ISSUE TITLE
Cloudflare script ignored Cloudflare

### ISSUE THREAD

**Issue by thatstaked** [Cloudbox/Cloudbox#124]
I had a wildcard setup with my previous DNS host. Script picked up and set up everything but Nextcloud.

**Comment by desimaniac** [comment]
I just ran it. Nextcloud was added to CF. Is your token filled in?

**Comment by thatstaked** [comment]
Bah. It was filled in, but with the wrong token. Sorry about. Just threw me for a loop when it everything else made it over. :)

**Comment by desimaniac** [comment]
Np.
