### ISSUE TITLE
Nginx Config

### ISSUE THREAD

**Issue by thor-mjolnir-90** [Cloudbox/Cloudbox#138]
Where would the nginx config be saved? I'm already using port 443 and would like to change what port external use is accessed from. Opening the proxy.conf in opt/nginx-proxy only has 4 lines 

```
# Increase max upload size
client_max_body_size 100G;
# Increase send timeout
send_timeout 100m;
```

**Comment by EnorMOZ** [comment]
If I understood your question properly, the config is stored on the container itself. It is dynamically generated. See https://github.com/jwilder/nginx-proxy for more info.  To use a different port you will have to change the virtual_port iirc on the role itself.

**Comment by zenjabba** [comment]
can confirm this fixes the problem
