### ISSUE TITLE
Frequent Crashing

### ISSUE THREAD

**Issue by ilikeadabox** [Cloudbox/Cloudbox#145]
Hi there - first of all you've done some amazing work here. Thank you so much. The problem I am discovering is seemingly random crashes. Sometimes I will run for hours with no issues, other times the entire server will crash within 10 minutes, requiring a reboot through the VPS provider panel. I cannot seem to find anything in the journalctl logs related to a kernel issue. I unfortunately do not have much more information to provide about it at the moment. Would be happy to provide what I can. Thanks

**Comment by desimaniac** [comment]
Plexdrive5 and docker containers, such as radarr, sonarr, and plex, use quite a bit of memory, are you limited by that?

**Comment by ilikeadabox** [comment]
Not impossible, I am running on a VPS by Hyper Expert - Specs are 8 vCPU, 8Gb RAM, and 160Gb of local storage. I did change the Plexdrive max chunks from 250 to 100.

**Comment by ilikeadabox** [comment]
Okay, good to know. Thanks for your time
