### ISSUE TITLE
Send rTorrent (and only rTorrent) traffic over VPN?

### ISSUE THREAD

**Issue by jorvi** [Cloudbox/Cloudbox#153]
I'm planning on running Cloudbox on a VPS with Gdrive as the storage. However, I also plan to run torrents on the VPS, and from what I've seen so far, VPSes are not exactly keen to allow torrents.
My plan was to only send rTorrent traffic over the VPN, however, I couldn't find a documented way to do this.
I've found this: https://github.com/binhex/arch-rtorrentvpn, which seems pretty awesome. It forces rTorrent to go over the PIA VPN, and includes a killswitch to prevent any leakage. Would it be possible to integrate this into CloudBox?

**Comment by jorvi** [comment]
Great :) thanks for the quick response!

**Comment by john626** [comment]
Can we have status update for this?

**Comment by Zoink5** [comment]
Any news on this one? 😄

**Comment by Maximus97** [comment]
This would be amazing :)

**Comment by desimaniac** [comment]
I dont see how I could make the install for this automated. Perhaps you can ask the ["Community"](https://discord.io/cloudbox) repo channel for someone to add it in for you.

**Comment by desimaniac** [comment]
Closing this as you can now post requests here: https://feathub.com/Cloudbox/Cloudbox

**Comment by inasua** [comment]
is there any plan to implement this?

most requested feature since ~1 year

**Comment by desimaniac** [comment]
No plans. 

You can either submit something to the Community Repo yourself or you can ask someone in the Community channel on Discord to add it in for you.
