### ISSUE TITLE
Plex TV Shows not displaying artwork / posters

### ISSUE THREAD

**Issue by rockcoolt** [Cloudbox/Cloudbox#156]
Hello,

In my series library the metadata has been found, but art artwork are not displayed.
![image](https://user-images.githubusercontent.com/18094312/41200383-fd6bb8e8-6ca3-11e8-8279-6eceab9d46b9.png)

I need your help

**Comment by l3uddz** [comment]
This was a bug with Plex. Please restart the Plex container and it will auto update. Then match the show again to force it to download metadata.

```
docker stop plex
docker start plex
```

**Comment by rockcoolt** [comment]
YES !!!!!!
Merci
