### ISSUE TITLE
NZBHydra 502 Bad Gateway

### ISSUE THREAD

**Issue by rockcoolt** [Cloudbox/Cloudbox#157]
Hello,
I have a issue with nzbhydra, i tryed to update Cloudbox, (https://github.com/Cloudbox/Cloudbox/wiki/Updating-Cloudbox)
but ,i still have the problem
![image](https://user-images.githubusercontent.com/18094312/41203046-58a0f27c-6cd2-11e8-98da-466e31df3500.png)

**Comment by desimaniac** [comment]
This issue was addressed in the #announcements channel of our [Discord](https://discord.gg/xmNYmSJ) chat server.

**Comment by rockcoolt** [comment]
Yes ,
Thank you
