### ISSUE TITLE
LazyMan Plex Plugin Not Working

### ISSUE THREAD

**Issue by bbbjorkman** [Cloudbox/Cloudbox#159]
According to [users on Reddit](https://www.reddit.com/r/LazyMan/comments/8iz5fh/live_mlb_on_plex_works_on_v11234973/dzeic55/?context=1), any Plex update to v1.13+ can't stream LazyMan on Ubuntu 16.04. Specifically, it looks like the binaries of ffmpeg bundled with the newest Plex are not compatible with the runtime on Ubuntu 16.04. Perhaps there could be a way to downgrade Plex to v1.12 for those of us who would like to use LazyMan?

**Comment by desimaniac** [comment]
In `settings.yml`, replace the Plex tag with the version you want to install. Then reinstall Plex. 

Example:
```
plex:
  tag: "1.12.3.4973-215c28d86"
  transcodes: "path/to/transcodes"
```

List of tags:
https://hub.docker.com/r/plexinc/pms-docker/tags/

**Comment by bbbjorkman** [comment]
Amazing, thanks! Sorry I missed that.

**Comment by desimaniac** [comment]
Welcome.
