### ISSUE TITLE
Please consider mapping the rutorrent plugins dir to /opt 

### ISSUE THREAD

**Issue by RXWatcher1** [Cloudbox/Cloudbox#16]
I didnt know where to place this request..here or https://github.com/l3uddz/docker-rutorrent

It is currently a challenge to add rutorrent plugins. You need to connect to the container and place your plugins into /usr/share/webapps/rutorrent/plugins.

If we can get this mapped to /opt/rutorrent/plugins or whatever then we can easily drop in plugins and they would be persistent. I have a few like ratio color that I use everywhere. This will change the font color of the ratio so I can easily see what my ratios are.

Thanks!

**Comment by Nottt** [comment]
@RXWatcher1  I think you can just edit the rutorrent role to add the mapping ?

**Comment by l3uddz** [comment]
Will take a look at this when I have a free moment.

**Comment by l3uddz** [comment]
We will be switching over to ruTorrent image by horjulf after some further compatibility tests. Hopefully this is something that can be added to the image without any adverse affects.

**Comment by ashtonlance** [comment]
How do I find the plugins folder now?
