### ISSUE TITLE
NZBGet Container

### ISSUE THREAD

**Issue by Landelor** [Cloudbox/Cloudbox#164]
This container doesn't seem to build properly the first time.
I have to run ansible-playbook with the nzbget tag a second time to get it to function properly.

**Comment by desimaniac** [comment]
I pushed out a fix in develop branch. Can you test that out?  

Youll need to remove the current container and delete/rename the opt folder.

**Comment by Landelor** [comment]
And then run with nzbget tag or cloudbox tag?

**Comment by desimaniac** [comment]
Just nzbget tag is fine.

**Comment by Landelor** [comment]
Using the nzbget tag already works though. It's with initial install that it doesn't work.

**Comment by desimaniac** [comment]
The issue is fixed regardless of what tag you use to install, so I'm closing this.

**Comment by Landelor** [comment]
Did a clean install with the change from develop. Just confirming that it is working as stated.
Regards,
