### ISSUE TITLE
"Folder is not writable by user hotio"

### ISSUE THREAD

**Issue by dansoaress** [Cloudbox/Cloudbox#168]
I have a problem when I add the TV folder in Sonarr and the Movies folder in Radarr. I'm getting the message "Folder is not writable by user hotio".

**Comment by dansoaress** [comment]
I must have made a mistake at the first installation. It's working now.

**Comment by OccultScientist** [comment]
> I must have made a mistake at the first installation. It's working now.

What was the fix for this? I'm having the same problem :(

**Comment by desimaniac** [comment]
Are you mounting any external drive/network path onto /mnt?

Also try deleting radarr_write_test.txt or sonarr_write_test.txt

**Comment by OccultScientist** [comment]
I have my local nas folders mounted in /mnt/local could that be causing the problem?

**Comment by OccultScientist** [comment]
Hi, just to let you know I managed to fix by rebuilding my rclone config and rebuilding plexdrive :)
Thanks for getting back to me

**Comment by desimaniac** [comment]
/mnt/local is fine. I've seen people mount the entire /mnt elsewhere. 

Just make sure it's writable. I've seen issues with cifs/samba.

**Comment by OccultScientist** [comment]
I rewrote my mounts in /etc/fstab rebooted and it worked!!
Thank you very much for your help @desimaniac :)
