### ISSUE TITLE
Plex library

### ISSUE THREAD

**Issue by bumjrah** [Cloudbox/Cloudbox#174]
I cannot seem to locate my media stored on an external drive. Am stuck when setting up plex libraries because of this. Please help.

**Comment by danjames92** [comment]
Cloudbox uses cloud storage.

See the wiki.

https://github.com/Cloudbox/Cloudbox/wiki/Prerequisites%3A-Cloud-Storage

**Comment by desimaniac** [comment]
You'll need to edit your unionfs.service file and replace /mnt/local with your external drive path.
