### ISSUE TITLE
plex_autoscan_url.sh Feature Request

### ISSUE THREAD

**Issue by andrewkhunn** [Cloudbox/Cloudbox#185]
@desimaniac: would it be possible for you to add a command-line switch to `/opt/scripts/plex_autoscan/plex_autoscan_url.sh` that returns the URL with no formatting or boilerplate text? I'd really appreciate not having to use `sed` to strip all the extra ANSI codes, etc.

**Comment by desimaniac** [comment]
Havent had the time to do this, but I was thinking that everything needs to be put into functions and then have a switch (eg --simple) to just output the url. If you want to submit something on that, let me know.

**Comment by desimaniac** [comment]
Done. 

You can now use it with `-s` or `--simple` arguments.
