### ISSUE TITLE
Wiki update - Updating Cloudbox

### ISSUE THREAD

**Issue by coolwaterblue** [Cloudbox/Cloudbox#198]
The dependencies URL has changed to update Cloudbox. Although it is documented on the 'Install:Dependencies' page https://github.com/Cloudbox/Cloudbox/wiki/Install%3A-Dependencies the 'Updating Cloudbox' page needs to be amended https://github.com/Cloudbox/Cloudbox/wiki/Updating-Cloudbox

**Comment by desimaniac** [comment]
Done. Thx.
