### ISSUE TITLE
settings_updater.py

### ISSUE THREAD

**Issue by Biologist89** [Cloudbox/Cloudbox#199]
Hello. I'm trying to install and after running `sudo ansible-playbook cloudbox.yml --tags cloudbox` I get error `fatal: [localhost]: FAILED! => {"changed": false, "msg": "The script 'settings_updater.py' exited with an error when updating 'accounts.yml'. Check 'settings-updater.log' for details."}` I've checked settings-updater.log file but it is empty. I have done all steps for editing accounts.yml file. But I get this error every time. My VPS OS is ubuntu 18.04. Thanks

**Comment by desimaniac** [comment]
Can you run this command and paste the results?


```
/home/seed/cloudbox/roles/settings/files/settings-updater.py '/home/seed/cloudbox' 'accounts.yml.default' 'accounts.yml'
```

You will need to replace `seed` with your user name.

**Comment by Biologist89** [comment]
Seed also is my user name. Here is the results:
`Traceback (most recent call last):
  File "/home/seed/cloudbox/roles/settings/files/settings-updater.py", line 140, in <module>
    did_upgrade, upgraded_settings = upgrade_settings(default_settings, current_settings)
  File "/home/seed/cloudbox/roles/settings/files/settings-updater.py", line 102, in upgrade_settings
    sub_upgrade, res[k] = upgrade_settings(v, current[k], k)
  File "/home/seed/cloudbox/roles/settings/files/settings-updater.py", line 98, in upgrade_settings
    res[k] = current[k]
TypeError: string indices must be integers`

**Comment by desimaniac** [comment]
Can you paste your accounts.yml on an online yaml format validator and see if it finds an issue ?

**Comment by Biologist89** [comment]
I've used yamllint[dot]com for checking and validating the accounts.yml file. It found some errors and rearranged yml file, However problem still persists after editing file. Thanks again for your quick and clear responses. Respects.

**Comment by desimaniac** [comment]
I'm not sure what's up. But i guess you can just add `--skip-tags settings` to the command to just skip that part. It only adds new settings from the .default files in.

**Comment by Biologist89** [comment]
Another error happened this time.
 `fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'nzbget' is undefined\n\nThe error appears to have been in '/home/seed/cloudbox/roles/pre_tasks/tasks/clean_paths.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Remove trailing slash from old downloads paths\n  ^ here\n"}`
Maybe I'm not lucky enough to use these cool tools. Thanks again for your time and hard work.

**Comment by desimaniac** [comment]
That's something that I may need to fix later. For now put back the following in settings.yml

```
nzbget:
  downloads: 
rutorrent:
  downloads:
```

But you can leave it blank.
