### ISSUE TITLE
Discord CloudBox Invite Broken / Not Working

### ISSUE THREAD

**Issue by clovisd** [Cloudbox/Cloudbox#202]
Title says it all, link on frontpage readme doesn't work/expired.

**Comment by desimaniac** [comment]
Works for me.

On Wed, Sep 12, 2018 at 8:35 AM Clovis <notifications@github.com<mailto:notifications@github.com>> wrote:

Title says it all, link on frontpage readme doesn't work/expired.

**Comment by desimaniac** [comment]
Works for me.
