### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by SecretSmiles** [Cloudbox/Cloudbox#207]
Yes, I know. It's probably not a Cloudbox issue, but I can't setup Plexdrive as shown in the wiki.
I already tried a fresh install of Ubuntu 18.04.

I've setup everything exactly as instructed in the wiki. But when I run this command:
`/opt/plexdrive/plexdrive mount -v 3 --refresh-interval=1m --chunk-check-threads=8 --chunk-load-threads=8 --chunk-load-ahead=4 --max-chunks=100 --fuse-options=allow_other,read_only --config=/opt/plexdrive --cache-file=/opt/plexdrive/cache.bolt /mnt/plexdrive`

I get this:

```
[OPT/PLEXDRIVE/PLEXDRIVE] [2018-10-08 14:45] INFO   : Mounting path /mnt/plexdrive
2018/10/08 14:45:43 mount helper error: fusermount: failed to access mountpoint /mnt/plexdrive: Transport endpoint is not connected
[OPT/PLEXDRIVE/PLEXDRIVE] [2018-10-08 14:45] DEBUG  : fusermount: exit status 1
```

Is there a fix for that? I don't know what's going on, already did my research but I'm a Linux noob ^^

Edit: Well, `fusermount -uz /mnt/plexdrive` and then re-mounting seems to fix it.

**Comment by desimaniac** [comment]
Reboot and/or rerunning the plexdrive or cloudbox tag would have done that as well
