### ISSUE TITLE
Single external IP, feeder/media install

### ISSUE THREAD

**Issue by coou** [Cloudbox/Cloudbox#210]
If cloudbox feeder/media split is installed on multiple servers where network has one external IP (ex. applicable to users at home with commodity hardware), only one server will have nginx ports forwarded for 80/443; in order to achieve desired workaround one would either have to configure nginx default.conf proxypass/server settings for remote host or have docker networking configured in overlay instead of bridge. Overlay networking further allows extensible use of 'splitting' containers. Would be nice to have an overlay networking option present in 'adv_settings.yml' to automate the process.

**Comment by desimaniac** [comment]
Can you work up something in a forked version ?
