### ISSUE TITLE
My isp blocks ports 443 and 80

### ISSUE THREAD

**Issue by lgrbueno** [Cloudbox/Cloudbox#220]
Can anyone help me how to change the ports that nginx use on cloudbox? My isp blocks the ports 80 and 443

**Comment by desimaniac** [comment]
Try changing those ports in the nginx proxy role.

**Comment by desimaniac** [comment]
Also this isn't the place to ask for anyone to help. You should join the Discord channel for that.

**Comment by lgrbueno** [comment]
sorry mate :D

**Comment by lgrbueno** [comment]
sorry!
