### ISSUE TITLE
Emby Beta support 

### ISSUE THREAD

**Issue by luxus** [Cloudbox/Cloudbox#221]
I just playing around with emby and notice that the beta is a big leap forward.(https://github.com/MediaBrowser/Emby.Releases/releases)
Could we have support for the latest and beta tag(https://hub.docker.com/r/emby/embyserver/) in adv_config?

**Comment by desimaniac** [comment]
I'll take alook.

**Comment by desimaniac** [comment]
And for future requests use: https://feathub.com/Cloudbox/Cloudbox

**Comment by RXWatcher1** [comment]
Thanks for this. I've been manually editing the role to play with the betas.
