### ISSUE TITLE
Backup Setting Removed settings.yml

### ISSUE THREAD

**Issue by nnord** [Cloudbox/Cloudbox#222]
Did you mean to remove the backup settings in the latest revisions of the settings.yml file? My nightly backup hasn't worked since updating last Thursday and I can't find any additional documentation on where you guys may have moved these settings.

**Comment by desimaniac** [comment]
Sorry I didn't get a chance to update the wiki about it. The settings went to backup_config.yml. I did make the announcement in our Discord channel. I take your not signed in there?

**Comment by nnord** [comment]
Thanks for your response. I wasn't familiar with Discord but I created an account and joined the Cloudbox server last night and will look for announcements and updates there in the future. Thanks for all the hard work and time you've put into this amazing product- it is certainly appreciated.

**Comment by desimaniac** [comment]
Yeah the Discord channel is quite active and has all a lot of resources there that may not be mentioned on the wiki.
