### ISSUE TITLE
Simple spelling error during update.

### ISSUE THREAD

**Issue by maximuskowalski** [Cloudbox/Cloudbox#225]
`TASK [settings : Exit so that user can check updated files and/or 'settings-updater.log'.] ********************************************************
Tuesday 20 November 2018  10:31:14 +1100 (0:00:00.078)       0:00:50.214 ******
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Cloudbox Installer will now exist."}
`

Exist should be exit.

**Comment by desimaniac** [comment]
Thanks.
