### ISSUE TITLE
error kernel : Reboot

### ISSUE THREAD

**Issue by zatuz** [Cloudbox/Cloudbox#227]
sudo ansible-playbook cloudbox.yml --tags feederbox
when installing cloudbox
the kernel is updated
And I lose all communication with the server.
check the following command on another server to verify the error
sudo ansible-playbook cloudbox.yml --tags kernel
And effectively it does not allow me to connect to the vps.
![error cloudbox](https://user-images.githubusercontent.com/39281593/48932487-d554bf80-eec1-11e8-9568-852e0cdd6bc3.png)

**Comment by desimaniac** [comment]
It reboots after kernel update.

![](https://i.imgur.com/VYP6Voi.png)

But if you cant get back on, then there is an issue with your particular vps setup and having the kernel updated to mainline kernel. 

You can do either of 2 things:

1) Add `--skip-tags kernel` to your commands. You can also put that at the bottom of `ansible.cfg` as:

   ```ini
   [tags]
   skip = kernel
   ```

2) Switch to `develop` branch (coming soon to `master`) and set kernel.version in `adv_settings.yml` to `disable`, that will also skip kernel updating.

**Comment by zatuz** [comment]
When installing cloudbox in Virtualbox and Google (GCE)
System: ubuntu 18.04
In the 2 I got the same detail. 
I will try again
If I resolve it, I mention it

**Comment by desimaniac** [comment]
Closing this since there isnt an issue. If you need further help, you can join the discord server.
