### ISSUE TITLE
Folder owner automatically changing & Plexdrive issue

### ISSUE THREAD

**Issue by nphil** [Cloudbox/Cloudbox#229]
I'm having an issue where everything in /mnt automatically changes ownership from my user to "82". This causes issues with basically everything from plex to rutorrent. I manually changed ownership a couple of times with chown -R user:user, but it reverts back to "82" automatically.

I'm also having an issue with plexdrive, it refuses to stay connected. Not sure if the two are related, but logs from plexdrive:

`Dec 07 07:43:51 SeattleBox systemd[1]: Started Plexdrive.
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : verbosity            : DEBUG
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : root-node-id         : root
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : config               : /opt/plexdrive
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : cache-file           : /opt/plexdrive/cache.bolt
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : chunk-size           : 10M
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : chunk-load-threads   : 8
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : chunk-check-threads  : 8
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : chunk-load-ahead     : 4
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : max-chunks           : 250
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : refresh-interval     : 1m0s
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : fuse-options         : allow_other,read_only
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : UID                  : 1000
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : GID                  : 1000
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : umask                : ----------
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : Opening cache connection
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : Authorizing against Google Drive API
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : Loading token from cache
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : Checking for changes
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : Getting start page token from cache
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : Last change id found, continuing getting changes (128104)
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] INFO   : First cache build process started...
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] INFO   : Mounting path /mnt/plexdrive
Dec 07 07:43:51 SeattleBox plexdrive[5016]: 2018/12/07 07:43:51 mount helper error: fusermount: failed to access mountpoint /mnt/plexdrive: Transport endpoint is not connected
Dec 07 07:43:51 SeattleBox plexdrive[5016]: [OPT/PLEXDRIVE/PLEXDRIVE] [2018-12-07 07:43] DEBUG  : fusermount: exit status 1
Dec 07 07:43:51 SeattleBox plexdrive[5016]: 
Dec 07 07:43:51 SeattleBox systemd[1]: plexdrive.service: Main process exited, code=exited, status=5/NOTINSTALLED
Dec 07 07:43:51 SeattleBox systemd[1]: plexdrive.service: Failed with result 'exit-code'`

I can't get the plexdrive folder to mount even with a systemctl restart, have to do a reboot and everything works fine until this happens again after a few hours.

Anyone else with this issue? Everything was working fine until recently.

**Comment by desimaniac** [comment]
Switch to develop branch and rerun the `core` tag. 

Since your issue is more of a support question, join the Discord server and you can get help from others there.

**Comment by nphil** [comment]
Thanks, I will try troubleshooting on discord!
