### ISSUE TITLE
PlexGuide VS Cloudbox?

### ISSUE THREAD

**Issue by qazero** [Cloudbox/Cloudbox#243]
I noticed that both PlexGuide and Cloudbox are very similar projects. I am trying to decide which project to deploy but I haven't found any documentation comparing the 2 and contrasting the differences to determine which one is better. Any suggestions, comments or feedback would be much appreciated. Thanks

https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server

**Comment by EnorMOZ** [comment]
Issues is not the place to ask this. Please join each projects' discord server and ask about the other project. See the different responses and make your own comparisons.

**Comment by nemchik** [comment]
I haven't used both, but you might just want to check the readme for each and see what they explain themselves as. Whichever one lines up better with what you're looking for is what you should use. You may also want to look around for reactions from the users in places like Reddit to see if there's any frequent or major issues other users face that might give you a hint as to the quality of each project and that may be a factor in your decision.
