### ISSUE TITLE
Netdata - Apparmor warnings

### ISSUE THREAD

**Issue by onelesd** [Cloudbox/Cloudbox#252]
`Ubuntu: Ubuntu 18.04.1 LTS`
`Docker: 18.09.1~3-0~ubuntu-bionic`

After adding the netdata container I noticed these apparmor warnings in the `journalctl -f` logs:

`Jan 29 01:30:41 nuc audit[11505]: AVC apparmor="DENIED" operation="ptrace" profile="docker-default" pid=11505 comm="apps.plugin" requested_mask="trace" denied_mask="trace" peer="unconfined"`

The warning was repeating several times a second, so I investigated and found that the netdata container needs to be started with a security_opt. See: https://hub.docker.com/r/netdata/netdata/

The change below fixes it. I can create a PR if you like.

```
diff --git a/roles/netdata/tasks/main.yml b/roles/netdata/tasks/main.yml
index a806124..3d904ec 100644
--- a/roles/netdata/tasks/main.yml
+++ b/roles/netdata/tasks/main.yml
@@ -40,6 +40,8 @@
       - SYS_PTRACE
     published_ports:
       - "127.0.0.1:19999:19999"
+    security_opts:
+      - "apparmor:unconfined"
     env:
       VIRTUAL_HOST: "netdata.{{domain}}"
       VIRTUAL_PORT: 19999
```

**Comment by desimaniac** [comment]
Yup. It’s bedn adddd to the develop branch [here](https://github.com/Cloudbox/Cloudbox/commit/952f11e24da288ca074ffd419da7a6eede279a75). Coming to master soon.
