### ISSUE TITLE
REQUEST sonarr/radarr move instead of copy

### ISSUE THREAD

**Issue by mitchelp** [Cloudbox/Cloudbox#263]
First of all, this isn't a issue. But just a request or a question on how I and maybe other can achieve this.

Well, the thing is, I got cloudbox running for a while now and it seems that radarr and sonarr are always copying the downloaded files. It would be awesome if they are able to move the completed files instead of copying them. This will save a lot of time in my opinion and unnecessary I/O. Cause the download location of nzbget and the final location of radarr/sonarr are on the same mount a copy shouldn't be necessary. So this can save a lot of processing time.

Maybe I do something wrong, or maybe this is something that can get figured out. I don't know. 

_Please feel free to close this one if this isn't a good location for this request/question. Please guide me to where it is a good location for this question/request._

**Comment by danjames92** [comment]
You can do this already and there is information on the wiki.

https://github.com/Cloudbox/Cloudbox/wiki/Downloading-into-the-unionfs-mount

**Comment by desimaniac** [comment]
Going to add some instructions in the wiki that will make this the default behavior.

**Comment by Tr4il** [comment]
Maybe there's something I'm missing here, but why isn't the default behaviour for usenet downloads to move the downloaded file into /mnt/local/Media? There's no need to copy and that way, you're not actually downloading into the unionfs mount. After this, it gets picked up by Cloudplow so moved to the cloud. Correct me if I'm wrong though, but I would like to know how to configure that.

**Comment by RXWatcher1** [comment]
Would sonarr/radarr still be picking it up, renaming it and triggering PAS
if it was downloaded directly to /mnt/local/Media before it was uploaded by
cloudplow?

You dont want cloudplow uploading it until it's properly tracked in
sonarr/radarr, renamed and PAS scanned.

**Comment by Tr4il** [comment]
Yea okay, but right now it's copying into /mnt/local/Media before radarr/sonarr get their hands on it right? Why shouldn't that be a move?

It's not a big issue in any way, it would just save a bit of time I guess. And I'm probably missing the whole clue here, so just leave the discussion for what it is if that's the case

**Comment by RXWatcher1** [comment]
No, Radarr/Sonarr are the guys that copy it into  /mnt/local/Media.

see the diagram at the bottom of this page.
https://github.com/Cloudbox/Cloudbox/wiki/Basics%3A-Introduction

Media is downloaded into /mnt/local/downloads/nzbs/nzbget and then picked
up by sonarr/radarr, copied to /mnt/local/Media, renamed, pas triggered.
Cloudplow comes and cleans out /mnt/local/Media post all of that.

**Comment by RXWatcher1** [comment]
It is a move...my fault on the wording. I will leave it up to others to
come in here and answer why its setup the way it is.
I dont ever download directly into the union so I can't say.

You should join the discord..probably a better place for this.

**Comment by Tr4il** [comment]
I will.

**Comment by desimaniac** [comment]
Why wasn’t this the default config to download into a UnionFS mount right from the get-go, see warning on the previous linked wiki [page](https://github.com/Cloudbox/Cloudbox/wiki/Downloading-into-the-unionfs-mount).
