### ISSUE TITLE
merferfs and feeder mount bug.

### ISSUE THREAD

**Issue by Chudz** [Cloudbox/Cloudbox#270]
Not sure if you are already aware but thought I would report it anyway.

There is a small bug with mergerfs on the develop branch if  your using a Mediabox/Feederbox setup. Basically the feederbox mount is still using unionfs. I added it into the mergerfs.service myself for now.

**Comment by desimaniac** [comment]
Yeah it needs updating.

**Comment by desimaniac** [comment]
Updated
