### ISSUE TITLE
Cloudplow Remote Duplicate Directory

### ISSUE THREAD

**Issue by theweasley** [Cloudbox/Cloudbox#282]
**Background:** I'm running Cloudplow with Cloudbox on a remote server to manage my plex library. I have a Gdrive linked to this remote server where Cloudplow uploads all the media.

**Problem:** My Gdrive Media/Movies folder already had movies in it prior to me connecting it to the remote server. I also downloaded higher-res versions (4K) of the same movies on my remote server. I want to keep both versions for multiple playback options on plex (1080p and 4K). The names of the movie folders are the same on both the remote server and the Gdrive. So now when Cloudplow tries to upload to Gdrive, it gives a Duplicate Directory error and ignores the upload for these movies with multiple versions.

**Question:** How can I disable this feature in Cloudplow such that the duplicate folders are not ignored and Cloudplow uploads and merges the files into the same duplicate folder on Gdrive?

**Comment by desimaniac** [comment]
Closing this since I answered this on the Cloudpow repo.
