### ISSUE TITLE
Plex_Dupefinder Improvements

### ISSUE THREAD

**Issue by dcplaya** [Cloudbox/Cloudbox#287]
When I installed plex_dupefinder I noticed the following things that may or may not be bugs

1) Plex token isnt automatically put into the config.json
2) With an Ansible vault, to install plex_dupefinder you must specify `--vault-id ~/.ansible_vault`. Ideally this should be taken care of like the other roles
3) Skip list should probably include `"SKIP_LIST": ["/Plex Versions/"],` so it doesn't delete copies of Plex converted files

**Comment by desimaniac** [comment]
```
1. Plex token isnt automatically put into the config.json
```

Need logs to see why. FYI, it is currently only doing this to new installs not existing ones. 

```
2. With an Ansible vault, to install plex_dupefinder you must specify --vault-id ~/.ansible_vault. Ideally this should be taken care of like the other roles
```

Just tested and it works fine with my encrypted ansible_vault file. Since `ansible.cfg` points to `~/.ansible_vault`, make sure you run it as the user (not in `sudo su`). 

PS There is nothing special about this role that would not make it work. 

```
Skip list should probably include "SKIP_LIST": ["/Plex Versions/"], so it doesn't delete copies of Plex converted files
```

I can add that to default config. But for curiosity, what is the full path to this?

**Comment by dcplaya** [comment]
1. What log file do you need to see? This was basically a new install, i didnt have plex_dupefinder installed yet on this server and I used the CB tag to install it. I can copy my config and uninstall it and do a fresh install of PDF to get you the log. 

2. Hmmm...my issue may have been because I was `sudo su`. Ill try again, I had multiple tmux sessions open and may have used the wrong one

3. The `"/Plex Versions/" is a catch all since I store my Plex Versions inside the source directory (ie, `/mnt/unionfs/Media/Movies/Movie Name (Year)/Plex Versions/`). An actual example path for me would be `/mnt/unionfs/Media/Movies/Avengers Infinity War (2018)/Plex Versions/Optimized for TV/Avengers_ Infinity War (2018).mp4`. I believe when I first set that up, @l3uddz told me to do it that way but there may be a better way now.

**Comment by desimaniac** [comment]
Run `--tags plex_auth_token` and it should show your token. When you run a role you can add `-vv` to show you more info during the install - the log that it outputs (even without -vv) is what is helpful.
