### ISSUE TITLE
Cloudbox Update/Install error with ubuntu snap packages

### ISSUE THREAD

**Issue by fruxi** [Cloudbox/Cloudbox#296]
I got following error during an Cloudbox update:

```
TASK [user : Reset ownership of '/home/seed/' path] ********************************************************************************************************************************************************************
Saturday 27 April 2019  16:24:54 +0200 (0:00:00.053)       0:00:28.601 ********
fatal: [localhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: [Errno 30] Read-only file system: '/snap/filebot/24/usr/share/themes/Adwaita'", "owner": "root", "path": "/snap/filebot/24/usr/share/themes/Adwaita", "size": 64, "state": "directory", "uid": 0}
```

I'm using snap packages (e.g. filebot) which creates a "read-only" filesystem for the application.
 What I found so far is, that some folders/files (e.g. /home/seed/snap/filebot/24/.themes -> /snap/filebot/24/usr/share/themes) in the home folder are symlinked to /snap/filebot/.... and maybe ansible is following the symlinks and trying to change the permissions of these files as well.

My solution was to move the /home/seed/snap folder away for the update and move it back afterwards.

**Comment by desimaniac** [comment]
Updated it to skip symlinks during that task. It’s current in dev branch.

**Comment by fruxi** [comment]
It's working now!
