### ISSUE TITLE
Lost permissions on remote folder since update[Bug]

### ISSUE THREAD

**Issue by OccultScientist** [Cloudbox/Cloudbox#297]
Since the latest update, my media files are all showing unavailable.
After further investigation it seems that the /mnt remote folder has lost it's permissions.

![image](https://user-images.githubusercontent.com/36533486/57281418-ddd13900-70a2-11e9-887f-1f6f88e3f846.png)

Using Ubuntu 18.04.

Any ideas?

**Comment by EnorMOZ** [comment]
This is not a bug in CB. Run `sudo umount /mnt/remote` and/or  `sudo /bin/fusermount -uz /mnt/remote` to un-mount the directory properly.  Basically the underlying fuse interface took a dump.

**Comment by OccultScientist** [comment]
You absolute legends, that worked perfectly!
Sorry for reporting as a bug, wasn't sure as it happened with the update.

Many thanks and keep up the great work.

**Comment by OccultScientist** [comment]
Hey @EnorMOZ 

Any idea why I need to keep repeating this after each reboot?

**Comment by desimaniac** [comment]
If you have a support question, please use [Discord Chat](https://discord.io/cloudbox).
