### ISSUE TITLE
wrong quotes in watchtower role

### ISSUE THREAD

**Issue by lonix** [Cloudbox/Cloudbox#298]
**Describe the bug**
The role watchtower run command use the wrong dobbleqoutes, so ansible treats then litterally. should be '"' and not '“'.

**To Reproduce**
1. install the role. 
2. start the container.
3. wait 5 mins. 
4. observe container, not running.

**Expected behavior**
Watchtower looking for updates.

**Additional context**
Pull-request incomming in 4 mins.

**Comment by desimaniac** [comment]
Resolved by #299
