### ISSUE TITLE
Plex Nginx Reverse Proxy Settings

### ISSUE THREAD

**Issue by hartertw** [Cloudbox/Cloudbox#3]
Please consider integrating the Plex Nginx Reverse Proxy Settings found in the follow github project.

https://github.com/toomuchio/plex-nginx-reverseproxy

**Comment by desimaniac** [comment]
Plex is already behind an nginx reverse proxy.

**Comment by hartertw** [comment]
Yes but please take a look at the configuration settings in the link below.  They are optimized for Plex specifically.

https://github.com/toomuchio/plex-nginx-reverseproxy/blob/master/nginx.conf

**Comment by desimaniac** [comment]
I'll pass this on, but are you having any specific issues?
