### ISSUE TITLE
Homepage.php missing

### ISSUE THREAD

**Issue by sogeniusio** [Cloudbox/Cloudbox#301]
I'm following the guide in the wiki and the final step is st configure Organizr. It requires us to use homepage.php. But this file seems to be missing. Please advise.

**Comment by desimaniac** [comment]
The guide needs updating.

**Comment by drod3763** [comment]
There are a few things the guide is out of date on. I wonder if there is an ETA on the updates. A couple of the apps have a completely different UI now.

**Comment by taylorbanks** [comment]
> There are a few things the guide is out of date on. I wonder if there is an ETA on the updates. A couple of the apps have a completely different UI now.

Yeah, Organizr doesn't really function anymore (or function well) out of the box, in its current state.

**Comment by loop** [comment]
Instead of `homepage.php` use `api/?v1/homepage/page` as the tab url.

**Comment by saltydk** [comment]
Seems to have been resolved.
