### ISSUE TITLE
Ombi isn't starting anymore

### ISSUE THREAD

**Issue by MJehli** [Cloudbox/Cloudbox#302]
**Describe the bug**
It won't start. (See log)

**To Reproduce**
(Re-) Install Ombi.

**Logs**
Link to debug or trace log files.

https://pastebin.com/Caf2KuSx

**System Information**

 - Cloudbox Version: [Master (latest)]
 - Operating System: [Ubuntu Server 18.04 LTS]
 - Linux Kernel: [4.15.0]

**Comment by desimaniac** [comment]
Fix is in develop branch.
