### ISSUE TITLE
python-plexlibrary tag resets crontab tasks

### ISSUE THREAD

**Issue by zhdenny** [Cloudbox/Cloudbox#303]
**Describe the bug**
Run the python-plexlibrary tag......installs just fine.....but it wiped my current lists of tasks inside "crontab -e" and replaced them with just the python-plexlibrary daily task

**To Reproduce**
1. crontab -e........note your current list of tasks
2. run the python-plexlibrary tag
3. crontab -e......note your tasks have been wiped and only thing there is now python-plexlibrary

**Expected behavior**
If this script is supposed to add something to crontab.....just add it to the end.....instead of wiping entire list of crontab tasks

**System Information**

 - Cloudbox Version: Master (latest)
 - Operating System: [e.g. Ubuntu Server 18 LTS]
 - Linux Kernel: [e.g. 5.x]

**Comment by desimaniac** [comment]
That's how ansible works. When you modified the cron task, you should have removed the comment that was added by it.
