### ISSUE TITLE
Enable an option for wildcard SSL certificates 

### ISSUE THREAD

**Issue by MollyBe** [Cloudbox/Cloudbox#305]
Cloudbox is growing and the default build requires nearly a dozen sub-domains and their corresponding SSL certificates, the community aspect of Cloudbox is also growing; leading to even more demand for single domain SSLs'. 

If we enabled the option to use a wildcard SSL certificate instead of using single domain SSLs' for every sub-domain we could simplify certificate management

**Comment by sogeniusio** [comment]
I support.

**Comment by JigSawFr** [comment]
@desimaniac that's not effective now in recent commits ?

**Comment by desimaniac** [comment]
It is in dev branch, but I was waiting on that to become master before reporting here and closing it.

**Comment by saltydk** [comment]
Closing this as it is already in the develop branch.
