### ISSUE TITLE
TorrentCleanup.py / Sonarr:  "Arguments are no longer supported for custom scripts" 

### ISSUE THREAD

**Issue by platbr** [Cloudbox/Cloudbox#306]
Arguments are no longer supported for custom scripts for Sonarr.
<img width="757" alt="Screen Shot 2019-07-02 at 11 27 34" src="https://user-images.githubusercontent.com/4853326/60520830-74456380-9cbc-11e9-9a02-28d282d7bff0.png">

**Comment by desimaniac** [comment]
Can you try this? 

```python
import logging
import os
import sys

# Setup logger
log_filename = os.path.join(os.path.dirname(sys.argv[0]), 'cleanup.log')
logging.basicConfig(
    filename=log_filename,
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s - %(message)s'
)
log = logging.getLogger("TorrentCleanup")

# Retrieve Required Variables

if os.environ.get('sonarr_eventtype') == "Test":
    sys.exit(0)
elif 'sonarr_episodefile_sourcepath' in os.environ:
    sourceFile = os.environ.get('sonarr_episodefile_sourcepath')
    sourceFolder = os.environ.get('sonarr_episodefile_sourcefolder')
elif 'radarr_moviefile_sourcepath' in os.environ:
    sourceFile = os.environ.get('radarr_moviefile_sourcepath')
    sourceFolder = os.environ.get('radarr_moviefile_sourcefolder')
elif 'lidarr' in sys.argv[1].lower():
    sourceFile = os.environ.get('lidarr_trackfile_path')
    sourceFolder = os.environ.get('lidarr_trackfile_folder')
else:
    log.error("Unable to determine cleanup requester. This must be either 'sonarr', 'radarr', or 'lidarr'.")
    sys.exit(0)

if os.path.exists(sourceFile) and os.path.isfile(sourceFile):
    # Scan folder for rar, if rar exists, remove sourceFile
    for found_file in os.listdir(sourceFolder):
        if found_file.endswith(".rar"):
            os.remove(sourceFile)
            log.info("Purged '%s'", sourceFile)
            break
```

**Comment by platbr** [comment]
@desimaniac 
I'm sorry, i was just following the documentation that instructed me to pass a path as a parameter but looking TorrentCleanup.py code i guess it is not necessary anymore. It's only necessary to update the doc.

I didn't test your code because interface input for path is missing on sonarr, so it will fail.

**Comment by platbr** [comment]
Im closing it because is just a doc problem.

**Comment by desimaniac** [comment]
Actually code needs to be modified (it currently needs arguments) and that’s why I was having you test changes.

**Comment by robinkooli** [comment]
Where should the code be put in?

**Comment by desimaniac** [comment]
Replace the one in `/opt/scripts/torrents/TorrentCleanup.py`

**Comment by atilling** [comment]
I updated the Python as per desimaniac, I will  provide feedback when I see if it works or not

**Comment by HitsvilleUK** [comment]
Seems to be working as expected now. 
Thanks for pointing this fix out on discord the other day @atilling

**Comment by Soulplayer** [comment]
I edited the file but it keeps giving me an error:
`19-8-5 20:01:12.9|Debug|Api|[POST] /api/v3/notification/test: 400.BadRequest (20 ms)
19-8-5 20:01:18.0|Debug|CustomScript|Executing external script: /scripts/torrents/TorrentCleanup.py
19-8-5 20:01:18.0|Debug|TorrentCleanup.py|Starting /scripts/torrents/TorrentCleanup.py 
19-8-5 20:01:18.4|Error|TorrentCleanup.py|/usr/bin/env: â€˜python\râ€™: No such file or directory
19-8-5 20:01:18.4|Debug|CustomScript|Executed external script: /scripts/torrents/TorrentCleanup.py - Status: 127
19-8-5 20:01:18.4|Debug|CustomScript|Script Output: 
8/5/2019 6:01:18 PM - Error - /usr/bin/env: â€˜python\râ€™: No such file or directory
19-8-5 20:01:18.4|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Script exited with code: 127`

**Comment by desimaniac** [comment]
@Soulplayer Try this: https://github.com/l3uddz/TorrentCleanup/blob/develop/TorrentCleanup.py

**Comment by Soulplayer** [comment]
Still getting errors:

> -8-8 21:09:54.4|Debug|CustomScript|Executing external script: /scripts/torrents/TorrentCleanup.py
> 19-8-8 21:09:54.4|Debug|TorrentCleanup.py|Starting /scripts/torrents/TorrentCleanup.py 
> 19-8-8 21:09:54.8|Debug|CustomScript|Executed external script: /scripts/torrents/TorrentCleanup.py - Status: 255
> 19-8-8 21:09:54.8|Debug|CustomScript|Script Output: 
> 
> 19-8-8 21:09:54.8|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
>  -- Script exited with code: 255

**Comment by desimaniac** [comment]
Does this error happen when you hit `Test` or after download/import ?

**Comment by Soulplayer** [comment]
I cannot save the settings without testing it. So I cannot see if it works with download/import.

**Comment by desimaniac** [comment]
Delete that custom script and create a new one.

**Comment by desimaniac** [comment]
CB will now pull the updated  'TorrentCleanup.py' from its own repo.
