### ISSUE TITLE
Syncthing Support

### ISSUE THREAD

**Issue by jhthenerd** [Cloudbox/Cloudbox#308]
---

**Describe the problem**
Only Resilio Sync is supported, when the open-source alternative Syncthing works just as well, and also has a [docker image.](https://github.com/linuxserver/docker-syncthing)

**Describe any solutions you think might work**
Supporting Syncthing would be nice to have, especially for those who prefer using open-source technologies.

**Comment by RXWatcher1** [comment]
You can add it to the Community repo yourself and we can then all enjoy it.
Desi is very picky about what goes into CB itself which is why he created
the Community repo so we can all add the apps we find useful that he might
not want to add to CB itself.

**Comment by Sibicle** [comment]
Bump on this one from me. Resilio Sync has become a corporate money grab. I paid for it, only to realize that they have no intention of listening to the community to make the product better. Would be nice to see the open source + more functional alternative supported in the base repo.

**Comment by saltydk** [comment]
Closing this issue as I agree with RX about it being more relevant to the Community repo than this one. Resilio is no longer a part of the repo as of develop and once that becomes master Resilio will only exist in Community.
