### ISSUE TITLE
Cors on Netdata - Unable to find nginx default or apache htaccess

### ISSUE THREAD

**Issue by emwedk** [Cloudbox/Cloudbox#310]
Hey - i'm having an issue which i was having with Plexpy aswell, where XML request is blocked by Cors and i will get a 401;
Access to XMLHttpRequest at '<website>' from origin '<website>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I managed to find the default file for both plexpy and (i guess docker) where i updated it with;
add_header Access-Control-Allow-Origin "*";
which resolved my issue with plexpy.

However, i'm not able to find the same file for netdata.
i'm using "sudo updatedb" and "locate" to find the files which also looks inside docker containers.

I've also tried to find htaccess, but with no luck.

Anyone got any suggestions?

**Comment by desimaniac** [comment]
Try to add it to `/opt/nginx-proxy/vhost.d/netdata.YOURDOMAIN.LTD`
