### ISSUE TITLE
Nvidia PPA 

### ISSUE THREAD

**Issue by danialmoghaddam** [Cloudbox/Cloudbox#312]
---

**Describe the problem**
Installing Nvidia driver using .sh installer is not recommended by Nvidia and could break the system.

**Describe any solutions you think might work**
It is recommended to use graphics-driver PPA installation:

`ubuntu-drivers devices`

== /sys/devices/pci0000:00/0000:00:02.3/0000:04:00.0 ==
modalias : pci:v000010DEd00001B82sv00003842sd00006775bc03sc00i00
vendor   : NVIDIA Corporation
model    : GP104 [GeForce GTX 1070 Ti]
driver   : nvidia-driver-430 - distro non-free recommended
driver   : nvidia-driver-390 - distro non-free
driver   : xserver-xorg-video-nouveau - distro free builtin

`apt install nvidia-driver-430`

We could use the `recommended` to pick the best suitable driver.

**Example of driver installation step in nvidia_driver.yml **
name: Install Nvidia drivers
shell: apt-get install nvidia-driver-430 --yes
register: driver_install
ignore_errors: yes

**Comment by desimaniac** [comment]
You can specify custom version now c1b048fed25fcfab3024d2bac2e0f44b7915274a or even ignore driver install 9fbc54f2558defe5e5c35a4480ff8a3ed264ccdc

**Comment by desimaniac** [comment]
Could maybe add a keyword for 'recommended' and have it installed via apt instead.

**Comment by desimaniac** [comment]
A
