### ISSUE TITLE
Error starting nginx container: unable to set hairpin mode

### ISSUE THREAD

**Issue by Sibicle** [Cloudbox/Cloudbox#316]
**Describe the bug**
When running the cloudbox install scrip, the nginx container fails to start

**To Reproduce**
1. Follow installation instructions
2. Run coudbox install command
3. See error

**Logs**
Link to debug or trace log files.
```
Error starting container 7fd2c45c93867571da358ee67eef19087ea7979702358a3cbf2b08940d151363: 500 Server Error: Internal Server Error ("failed to create endpoint nginx-proxy on network cloudbox: unable to set hairpin mode on vethb1f6c19 via netlink: address family not supported by protocol")
```

**System Information**
 - Cloudbox Version: **latest**
 - Operating System: **Ubuntu Server 18.04 LTS**
 - Linux Kernel: **4.15.0**

**Additional context**
100% fresh install on Ubuntu Server 18.04. Tried whole process multiple times.

**Comment by abien** [comment]
Might be worth mentioning that the interface `vethb1f6c19` most likely belongs to a Virtuozzo or OpenVZ Container. It's not a full blown VM. Their "Docker in Container" support is known to be unreliable when using advanced functionality.
