### ISSUE TITLE
Raddar nightly in doc but develop installed

### ISSUE THREAD

**Issue by JigSawFr** [Cloudbox/Cloudbox#319]
**Describe the bug**
Hi guys, it's mentioned in wiki that branch for radarr is nightly, but when installed it's develop branch.
Question is, how to install real "nightly" branch instead of "develop" ?
Thank you

**To Reproduce**
- Install Radarr with ansible

**Expected behavior**
Install "nightly" branch of radarr

**Screenshots**
N/A

**Logs**
N/A

If issue occurs during Ansible playbook, run playbook with `-vv` to output detailed debug log.

**System Information**

 - Cloudbox Version: latest
 - Operating System: Ubuntu Server 16.04 LTS

**Additional context**
There is vars to enforce branch / version of apps delivered by cloud box ?

Thank you all !

**Comment by desimaniac** [comment]
There is an issue with nightly branch installing right now. You can switch branches via `adv_settings.yml` `suitarr.version`.  Choices are: `unstable`, `stable` = `default`, `image`.  Then rerun the `radarr` ansible tag.  Try `stable` or `image`.
