### ISSUE TITLE
Wiki: Install Dependencies step 2 using github fails creating default files

### ISSUE THREAD

**Issue by cbussa** [Cloudbox/Cloudbox#320]
Following Wiki step 2 on a newly installed and updated Debian 10 (Buster) system with XFCE:
git clone works, but following cp commands fail with "no file" because they've been moved to the default/ directory

Wiki page Install: Dependencies

Install: Dependencies
2. Download Cloudbox Repository
Note: If the above command fails, run the following:

git clone --recursive https://github.com/cloudbox/cloudbox.git ~/cloudbox; cd ~/cloudbox && cp -n ansible.cfg.default ansible.cfg; cp -n accounts.yml.default accounts.yml; cp -n settings.yml.default settings.yml; cp -n adv_settings.yml.default adv_settings.yml

**To Reproduce**
Running
git clone --recursive https://github.com/cloudbox/cloudbox.git ~/cloudbox; cd ~/cloudbox && cp -n ansible.cfg.default ansible.cfg; cp -n accounts.yml.default accounts.yml; cp -n settings.yml.default settings.yml; cp -n adv_settings.yml.default adv_settings.yml
... gives ...
Submodule path 'library/ansible-ghetto-json': checked out 'c5b85e6003d923bfda9cceb1bfc7b587e5bd905b'
cp: cannot stat 'ansible.cfg.default': No such file or directory
cp: cannot stat 'accounts.yml.default': No such file or directory
cp: cannot stat 'settings.yml.default': No such file or directory
cp: cannot stat 'adv_settings.yml.default': No such file or directory

**Expected behavior**
because in the GIT grab, those files are now all found in the default/ subdirectory.
Doing a "cp default/* .: BEFORE the 4 cp commands fixes it.

cp defaults/* .
cd ~/cloudbox && cp -n ansible.cfg.default ansible.cfg; cp -n accounts.yml.default accounts.yml; cp -n settings.yml.default settings.yml; cp -n adv_settings.yml.default adv_settings.yml
(no output)
ls *yml* -1
accounts.yml
accounts.yml.default
adv_settings.yml
adv_settings.yml.default
appveyor.yml
backup_config.yml.default
backup.yml
cloudbox.yml
settings.yml
settings.yml.default

**System Information**
Debian 10 current
Linux lap1 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
Cloudbox ?? Current -- it's not installed yet, doing dependencies for setup.

**Comment by desimaniac** [comment]
Updated the wiki page: https://github.com/Cloudbox/Cloudbox/wiki/Install:-Dependencies
