### ISSUE TITLE
Wiki: Ansible config file path info probably needs to be fully qualified and not ~

### ISSUE THREAD

**Issue by cbussa** [Cloudbox/Cloudbox#321]
**Describe the bug**
Following along the Wiki, 
Step: Install: Ansible Vault has me create the password in the user directory but then "sudo ansible-playbook" wants to use /root.  OR \: 3. Edit Ansible Config needs to use a fully qualified directory name instead of ~/filename to handle the EUID shift.

**To Reproduce**
Wiki: Step: Install: Ansible Vault

2. Create a Password File
create a password file.
vi ~/.ansible_vault  (DOESN'T say anything about users or ownership, places in current non-root user home)

3. Edit Ansible Config
add:
vault_password_file = ~/.ansible_vault (nothing about users, ownership, or hardcoding $HOME.  Points to a file using "current user's home directory"

Step: Install: Preinstall
To start the install, run this:
~/cloudbox$ sudo ansible-playbook cloudbox.yml --tags preinstall
[sudo] password: 
ERROR! The vault password file /root/.ansible_vault was not found

See above  Sudo shifts the effective ID to root but we're still in the user's directory where the .cfg file is.  Great but somehow ansible playbook is trying to use /root as ~ instead of old user's $HOME

**Expected behavior**
Either create .ansible_vault file in /root/ directory so that sudo ansible is happy,
*OR PROBABLY*
3. Edit Ansible Config
vault_password_file = ~/.ansible_vault
... needs to instead use a fully qualified path pointing to the non-root user's directory.
So: echo "vault_password_file = $HOME/.ansible_vault" >>  ~/cloudbox/ansible.cfg
Usernames don't have internal spaces, do they?

**System Information**
Cloudbox Version: current, installing
debian 10 Buster
Linux lap1 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux

**Comment by desimaniac** [comment]
Yeah that's an issue with Debian - the tilde not expanding to the non-root user account. Not an issue with Ubuntu. 

But since $HOME is working in lieu of ~, we can switch that.
