### ISSUE TITLE
Home mount issue?

### ISSUE THREAD

**Issue by kasasmit** [Cloudbox/Cloudbox#323]
Heya,

When I started looking into Cloudbox I installed it a few cheap VPSes to test with (they only offered Debian so I used that) and had no trouble at all with installation/migration.

I upgraded to a Kimsufi dedi (KS-9) and they offer Ubuntu so I have switched over to it. The migration ran smoothly apart from some Plex Autoscan problems which I fixed up (I think) but I'm running into an issue with disk space reporting which wasn't happening in my test servers.

First I figured it could be from switching from Debian to Ubuntu so I started over fresh but the problem is still occuring. There should be 240GB disk space, but Sonarr, Radarr, Lidarr, etc all say they only have 19.1 GB space, and MOTD says this "Disk................: Used: 6.97 GB | Free: 12.13 GB | Total: 19.1 GB".

I checked disk space using df -H and this was the output

seed@hostname:~$ df -H
Filesystem      Size     Used      Avail     Use%      Mounted on
udev                8.4G          0      8.4G         0%      /dev
tmpfs              1.7G     2.0M       1.7G          1%      /run
/dev/md2        21G       7.5G       12G         39%     /
tmpfs              8.5G      8.2k      8.5G         1%       /dev/shm
tmpfs              5.3M          0      5.3M         0%      /run/lock
tmpfs              8.5G           0      8.5G         0%      /sys/fs/cgroup
/dev/md1        511M     83M    398M       18%      /boot
/dev/md3        274G    92M     260G         1%      /home
local:remote   1.2P     189G       12G        95%     /mnt/unionfs
google:           1.2P     182G       1.2P           1%     /mnt/remote
tmpfs              1.7G           0       1.7G          0%     /run/user/1000

I am guessing it's looking at /dev/md2 but it's meant to be looking into /dev/md3? I tried looking through the wiki and past issue posts but wasn't able to find anything to deal with this kind of thing. I'm not sure how to best get Cloudbox to work with this so any help would be incredible.

Thank you!

**Comment by kasasmit** [comment]
Ok, with some sleep and more research, I think I figured it out. Kimsufi/SYS/OVH servers put /home in a different partition so I reinstalled the server and removed the /home partition and added the remaining space to /

I was looking at one of my other servers with OneProvider (running on Debian) and it didn't have a separate /home partition which I'm guessing is why I didn't run into this problem earlier.

Running "df -h" on the OneProvider server:

root@oneproviderserver:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M  8.5M  789M   2% /run
/dev/sda3       915G  6.6G  862G   1% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda1       476M   36M  412M   8% /boot
local:remote    1.1P  177G  862G  17% /mnt/unionfs
google:         1.0P  170G  1.0P   1% /mnt/remote
tmpfs           798M     0  798M   0% /run/user/0

After the reinstall, the Kimsufi server is showing this (missing google since rclone hasn't been setup):

root@kimsufiserver:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  980K  1.6G   1% /run
/dev/md2        274G  1.9G  259G   1% /
tmpfs           7.9G     0  7.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/md1        487M   79M  379M  18% /boot
tmpfs           1.6G     0  1.6G   0% /run/user/0

Anyway in case this helps someone in the future, I had to change the install settings as below:

Check "Custom installation"
![image](https://user-images.githubusercontent.com/15816414/65368324-d772e080-dc82-11e9-9cd2-fa7d2ae97d22.png)

Delete the /home partition:
![image](https://user-images.githubusercontent.com/15816414/65368332-e9ed1a00-dc82-11e9-9ca7-f4e2c9b95c32.png)

Change the / partition to have the remaining space:
![image](https://user-images.githubusercontent.com/15816414/65368334-ef4a6480-dc82-11e9-9469-adee4fb002d3.png)

I really like the community here so if I can help in anyway (doco etc) please let me know!

**Comment by desimaniac** [comment]
Thanks! That is helpful.
