### ISSUE TITLE
Lost password of bazarr

### ISSUE THREAD

**Issue by GautierT** [Cloudbox/Cloudbox#324]
Hi,
I added a form based password to Bazarr but i lost it.
How to reset a docker images ?
I try stopping the image then `docker rmi -f IMAGE_ID` then re-installing with the correct tag but this doesn't work (password still present).
Thanks

**Comment by chazlarson** [comment]
The config data for a given docker image is typically stored in `/opt/APPNAME`.  If that directory already exists, the tag will not overwrite it.

In your case, delete or rename `/opt/bazarr` and then rerun the tag.  You should be back to the brand new starting point.

**Comment by GautierT** [comment]
Indeed !
Thanks a lot !


Le lun. 23 sept. 2019 à 19:05, Chaz Larson <notifications@github.com> a
écrit :
