### ISSUE TITLE
Sonarr no longer has "on download" option for custom scripts

### ISSUE THREAD

**Issue by ignitenz** [Cloudbox/Cloudbox#325]
https://github.com/Cloudbox/Cloudbox/wiki/Install%3A-Sonarr tells us to set the custom script to fork "On download" and "on upgrade" but the "on download" option is not there anymore. What should we do in place of this?

**Comment by drod3763** [comment]
On Import I think

**Comment by ignitenz** [comment]
Yeah, that works.

**Comment by desimaniac** [comment]
Updated wiki.
