### ISSUE TITLE
Plexrequest install failed

### ISSUE THREAD

**Issue by droidbizz** [Cloudbox/Cloudbox#326]
When try to install plexrequest the following error apear during install:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image linuxserver/plexrequests:latest - 404 Client Error: Not Found (\"pull access denied for linuxserver/plexrequests, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\")"}

Any help with it?

Thanks,

**Comment by RXWatcher** [comment]
@desimaniac Should remove this from CB

@droidbizz PlexRequests is dead..please use Ombi instead.
