### ISSUE TITLE
Transmission VPN and jdownloader

### ISSUE THREAD

**Issue by tarek369** [Cloudbox/Cloudbox#327]
Some use transmission with vpn if using public trackers, and jdownloader to download some other stuff .

If you plan to add those I can help and make a pull request in the coming days and then you can edit or tell me what need to be adjusted to meet your code standards!

**Comment by desimaniac** [comment]
We have a separate repo for community add-ons: https://github.com/Cloudbox/Community

There is already a Jjdownloader role there: https://github.com/Cloudbox/Community/tree/master/roles/jdownloader2

You can PR _Transmission with VPN_ role there if you'd like. Just add an entry to appveyor.yml as well and the PR will send it there to be tested.

**Comment by desimaniac** [comment]
There's a TransmissionVPN role in Community now.
