### ISSUE TITLE
Feature Request: Setting to switch between local/cloud access

### ISSUE THREAD

**Issue by inject00r** [Cloudbox/Cloudbox#328]
It would be nice making cloudbox available in the local network and not only purely through domains.

This would mean that the settings.yml should be enhanced by network: local/cloud.

As I already saw in the updated tasks changes like `published_ports: "{{ plex_docker_ports }}"` we could add a switch to read the ip:port configuration of each app through deployment.

**Comment by desimaniac** [comment]
Yeah that's what I'm working on. It's coming slowly..

**Comment by v1ct0rv** [comment]
Hi, Is there any way to enable local access? I have a configured server on my home, I can access through dns, but would be faster if I can access locally.

**Comment by After-Shock** [comment]
> Hi, Is there any way to enable local access? I have a configured server on my home, I can access through dns, but would be faster if I can access locally.

A few ways to accomplish this, expose the ports on the apps you wish to access locally, then access via ip:port.  Utilize hairpin NAT'ing or NAT reflection (as it's called by some) if your router/firewall supports it.  Use a local DNS solution, something as simple as pi-hole now has built in DNS capabilities.

**Comment by owine** [comment]
Not planned
