### ISSUE TITLE
Feature Request: SSH Hardening

### ISSUE THREAD

**Issue by owine** [Cloudbox/Cloudbox#330]
Would love some of the following SSH hardening options during server setup

- Specify a pubkey to provision for the provisioned user
- Specify an alternate port for sshd
- Disable root login via SSH
- Disable SSH login with passwords

**Comment by fragment1** [comment]
This is not a cloudbox feature... most server providers have supporting documents to assist with this. You could easily link folks to linode's ssh hardening document. I don't think the cloudbox wiki should include this as its not directly related.

**Comment by fragment1** [comment]
Or better yet, if you are insistent on this, write up a wiki page and submit it to desi for approval.

**Comment by fragment1** [comment]
I think this would be better served as a wiki page outlining how to do the above.

**Comment by mrhotio** [comment]
also check out https://github.com/skeeto/endlessh

**Comment by saltydk** [comment]
This seems more of a wiki thing for me and hopefully somebody decides to post a guide for this.
