### ISSUE TITLE
Issues with restored Plex library and settings?

### ISSUE THREAD

**Issue by Mnk3y** [Cloudbox/Cloudbox#332]
Hello, first of all **many thanks** for this great project.

I completely reinstalled my cloudbox and restored my old Plex settings by overwriting the Plex Media Server folder with my Plex Backup.

Unfortunately I can't connect to Tautulli. It tells me that "plex" is not a Plex server. Also, the webtools do not load.

Is this because I overwrote the Plex Media Server from an older Cloudbox installation?

**Do I have to change or adjust any IDs or tokens in a config?**

Plex on the other hand works without any problems and shows me the old name and all settings and so on.

Thanks in advance!

Edit: Sorry, the **webtools are working**, but Tautillus doesn't get a connection to the server if I enter "plex" as hostname.

**Comment by desimaniac** [comment]
Yeah it's an issue with the the current nightly version of Tautulli. 

Should be fixed with 1eb7e0ba7. 

Just update CB folder and run `plexpy` tag.

**Comment by Mnk3y** [comment]
Thank you, the server is now found. Unfortunately I get another error when I press "Verify".

`Websocket connection test failed: Handshake status 401`

And these warnings ...

`Unable to retrieve data for get_server_pref.`

`Failed to access uri endpoint /:/prefs. Status code 401`

`Tautulli Pmsconnect :: Unable to parse XML for get_local_server_name: 'NoneType' object has no attribute 'getElementsByTagName'.`

What can I do? I don't know. Thank you!

**Comment by desimaniac** [comment]
Try updating the repo and running the plexpy tag.
