### ISSUE TITLE
Feature Request: Multiple Traktarr Containers

### ISSUE THREAD

**Issue by vpatel9202** [Cloudbox/Cloudbox#333]
---

**Describe the problem**
Traktarr currently only allows syncing of Trakt lists with one root path for Radarr and one for Sonarr. It also only syncs to one instance of Radarr and Sonarr. This creates limitations for the following scenarios:

1. If you run multiple instances of Radarr/Sonarr, such as an instance for 4K content, you need to run just as many Traktarr instances.
2. If you have multiple root paths (e.g. "/movies/English_HD" and "/movies/Klingon_HD") you need to run a separate instance of Traktarr for each path. 

**Describe any solutions you think might work**
Traktarr is fairly lightweight and having multiple instances running is not an issue. Each instance would run from a separate config file but otherwise should be identical. This seems like an easy solution to implement without having to overhaul the Traktarr script to be able to manage multiple instances/roots.

**Additional context**
It's not difficult to manually start new Traktarr containers (possibly even just duplicate them within portainer), but having it as part of Cloudbox would be nice since it's possible to create new instances of Radarr/Sonarr for 4k content without doing so manually.

Edit: I also realized that Traktarr is not actually running in a docker container even though it exists in Cloudb0x's Dockerhub repos. I pulled it manually and mounted the /opt/traktarr directory to /config in the docker container. Running it with the given entrypoint and the command "run --run-now" seems to work fine as long as you authenticate Trakt outside the container. Is it not possible to use the container rather than installing to the system by default?

**For posterity, if anyone else wants to set up multiple dockers:**

1. Install traktarr via cloudbox per the wiki.
2. Navigate into /opt/traktarr and run `sudo python3 -m pip install -r requirements.txt`.
3. Create 3 folders: `mkdir /opt/traktarr/configs /opt/traktarr/logs /opt/traktarr/cache`.
4. Copy the sample config into the new config directory `cp /opt/traktarr/config.json /opt/traktarr/configs/instance1.json`. *Note: make as many copies as you need different instances of traktarr running, and name them whatever you want (instance1 is just a placeholder).*
5. Authenticate trakt for each config file: `python3 /opt/traktarr/traktarr.py --config /opt/traktarr/configs/instance1.json --logfile /opt/traktarr/logs/instance1.log --cachefile /opt/cache/instance1.db trakt_authentication`.
6. Go into each config and modify your Sonarr url to `http://sonarr:8989/` and the Radarr url to `http://radarr:7878`. *You will not be able to run these configs outside of Docker after this as the url is for the Docker network.*
7. Modify each config as needed.
8. Run the following docker command for each instance. *Note that these are the settings I use for traktarr but you can change the last line to whatever suits your needs (e.g. if you want to respect blacklist, just remove `--ignore--blacklist`).*

```
docker run -d \
  --restart=unless-stopped \
  --name='traktarr-instance1' \
  --net='cloudbox' \
  -e 'PUID'='1000' \
  -e 'PGID'='1000' \
  -e 'UMASK'='2' \
  -e TZ="America/New_York" \
  -e 'TRAKTARR_CONFIG'='/config/configs/instance1.json' \
  -e 'TRAKTARR_LOGFILE'='/config/logs/instance1.log' \
  -e 'TRAKTARR_CACHEFILE'='/config/cache/instance1.db' \
  -v '/opt/traktarr':'/config':'rw' \
  cloudb0x/traktarr:latest \
  run --run-now --ignore-blacklist --add-delay 5
```
9. Check `/opt/traktarr/logs/instance1.log` and make sure everything is working smoothly.

**Comment by saltydk** [comment]
Closing this as both sonarr and radarr now have the ability to handle lists. Reopen if you disagree.
