### ISSUE TITLE
TorrentCleanup.py broken on Lidarr only

### ISSUE THREAD

**Issue by kayladmae** [Cloudbox/Cloudbox#337]
**Describe the bug**
Cannot add TorrentCleanup.py as a custom script in Lidarr only, test/save fail with message 
"Script exited with code: 1"

**To Reproduce**
Lidarr -> Settings -> Connect -> New -> Custom Script

Name: Torrent Cleanup
Notification Triggers: (any)
Path: `/scripts/torrents/TorrentCleanup.py`

-> Click "save" or "test"

**Expected behavior**
Test should pass, script should save.

**Screenshots**
<img width="718" alt="Screen Shot 2019-12-11 at 6 13 02 PM" src="https://user-images.githubusercontent.com/1191071/70671530-efcf1780-1c41-11ea-8b19-5eac1d7b014c.png">

**System Information**

 - Cloudbox Version: Latest Master
 - Operating System: Ubuntu Server 18.04
 - Linux Kernel: 4.15.0-72-generic

**Additional context**
Using the script from `l3uddz/TorrentCleanup` at commit [2943cc417f](https://github.com/l3uddz/TorrentCleanup/tree/2943cc417fe5b9312129df21e3eb6d65e56df55b) (the initial commit) works correctly.

**Comment by desimaniac** [comment]
(Should be) Fixed in https://github.com/l3uddz/TorrentCleanup/commit/ab1943fe41481627260d3697f9cefdbe76544edd

Just run the `scripts` tag and it should pull the latest one.
