### ISSUE TITLE
Feature Request: Multiple mount support.

### ISSUE THREAD

**Issue by Silent-Remux** [Cloudbox/Cloudbox#339]
**Describe the problem**
Cloudbox can only use 1 remote out of the box. Multiple mount support natively would be useful.

**Describe any solutions you think might work**
Adding multiple options via commas (or some other syntax) in `settings.yml` could create additional systemd services and equivalent warmup files.
```
rclone:
  version: latest
  remote: remote1,remote2
```

**Comment by desimaniac** [comment]
I could do that. However, others are using a script that are generating SA files, creating remotes in Rclone config, and mounting them all. Not going to replicate all that.

**Comment by Silent-Remux** [comment]
> 
> 
> I could do that. However, others are using a script that is generating SA files, creating remotes in Rclone config, and mounting all of them in one go. Not going to be able to replicate all that. So need to see how useful the suggested feature will be for most.

Leave the configuration down to the user.

Have a step in the wiki that details where to place the json files. Have them set up their rclone remotes to point to the json files. This bit of a manual setup will get people to be handson and ensure it works.

The only bit of automation required is new service files and a chance of the RC port so it doesn't conflict. Maybe have the RC port count up.

**Comment by JigSawFr** [comment]
Love the idea, i was thinking about it some days ago. Example by splitting remotes for data / backup (2 different provider) and/or split data in multiple remote of the same providers (multiple gdrive for example).
Thank you for your work guys ! :)

**Comment by Silent-Remux** [comment]
Easily done by implementing something like smount.
