### ISSUE TITLE
Unsupported parameters during Plex install (Unsupported parameters for (docker_container) module: networks_cli_compatible)

### ISSUE THREAD

**Issue by claym** [Cloudbox/Cloudbox#340]
**Describe the bug**

**To Reproduce**
1. Pull latest from Github / Run Update command
HEAD is now at c7e2aeef Lidarr: Added default variables
2. sudo ansible-playbook cloudbox.yml --tags cloudbox
(also happens with just plex)

I get an error that states:

TASK [plex : Resources | Tasks | Docker | Create Docker Container] **
Sunday 29 December 2019  16:50:38 +0200 (0:00:00.191)       0:06:51.635 **
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (docker_container) module: networks_cli_compatible

More logs here: https://gist.github.com/claym/29e01972afc723ae54df6b3bde6f9721

**Comment by claym** [comment]
Required updating ansible (`sudo pip install 'ansible>=2.8,<2.9'`) then running the [dependencies script](https://github.com/Cloudbox/Cloudbox/wiki/Install%3A-Dependencies)

Things seems to be behaving. Anybody not checking discord and what not are going to run into issues.

**Comment by desimaniac** [comment]
Yup.. dev branch has moved to 2.8.

**Comment by JigSawFr** [comment]
@desimaniac not possible to add a task for running a subscript if needed to bump version of ansible ?

**Comment by desimaniac** [comment]
So that Ansible updates itself? If there was something only compatible with newer Ansible needed, it would error out before it started. 

Will add Ansible 2.8 to the dependency installer.
