### ISSUE TITLE
Nextcloud Setup

### ISSUE THREAD

**Issue by tarek369** [Cloudbox/Cloudbox#345]
I have this error in the wizard setup for nextcloud 

Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'oc_tarek'@'nextcloud.cloudbox' (using password: YES)

I used everything exactly as in the wiki page and i can connect to mariadb from mysql-client from any container 

**System Information**

 - Cloudbox Version: [Develop (latest)]
 - Operating System: [ Debian ]

**Comment by saltydk** [comment]
Username for the mariadb container is root. Password is password321. From your log it seems like you are using another user.

**Comment by tarek369** [comment]
No , actually I added the root and password321 but this user name is the user that I will create for nextcloud, so it seems that it connected to the database as root but couldn't make the user and give it privilege to create other tables and edit 

![Screenshot_20200111-122427](https://user-images.githubusercontent.com/36159724/72202903-72c7d580-346d-11ea-89a3-51cbe15b8a7e.jpg)

**Comment by saltydk** [comment]
Not sure if this works but this is a comment from discord:

> Nextcloud fix for some users: I shared this last week but i accidently removed my post: Seems to be a problem with getting nextcloud to work for some users. the usual instructions in the wiki results in a failed connection to mariadb. tried it with few different fresh server installs same issue. Also from looking at search results few people faced same problem: here's the fix in case someone searches for this later: follow the same instructions as the wiki including adding all the same passwords etc (password321). But FIRST try to connect to postgresql as the database option (this will fail ofcourse which is fine). Once it fails to connect then change database back to MySQL/MariaDB and try again (make sure all fields are filled in since changing tabs removes password which means you have to refill it)

**Comment by tarek369** [comment]
Well it doesn't make any sense! But it worked :) thank you so much 
Can I have the discord link ?

**Comment by desimaniac** [comment]
https://discord.io/cloudbox

**Comment by dazrave** [comment]
Weird solution that @saltydk shared but can confirm this also worked for me.

I assume trying to connect to postgresql automatically deletes config/settings stored for mariadb meaning you can try again completely clean, or something?

**Comment by JigSawFr** [comment]
Bug confirmed too after fresh install.
Workaround works great (even if it's pretty strange !)
