### ISSUE TITLE
Cloudbox Backup - Postpone if a Plex streams is active

### ISSUE THREAD

**Issue by JigSawFr** [Cloudbox/Cloudbox#346]
Hi there, it could be great to postpone backup in case of an active streams on Plex.
As already effective with cloudpl0w with throttle feature :)

Thank you !

**Comment by saltydk** [comment]
Setup btrfs and it won't matter.

**Comment by desimaniac** [comment]
Ansible is made to do a task and just stop. So can’t hold off completion of a task indefinitely since it doesn’t come with a scheduler like that. Could have it where it skips a backup or maybe delays it max for an hour or two before giving up.
