### ISSUE TITLE
Enable magnet links

### ISSUE THREAD

**Issue by yleflour** [Cloudbox/Cloudbox#347]
**Describe the bug**
After installing, I found out that rutorrent wouldn't download magnet links provided by public indexer and using public trackers.

**To Reproduce**
1. Install Cloudbox
2. Use a public indexer providing magnet links

**Expected behavior**
I believed magnet links would work out of the box

**Solution**
UDP is disabled by default in `/opt/rutorrent/rtorrent.rc` to fix this I had to set

```
trackers.use_udp.set = yes // previously "no"
```

I believe it should be changed in `roles/rutorrent/tasks/settings/static.yml` but don't know if the current config is intended

**Comment by RXWatcher** [comment]
This is on purpose. Cloudbox out the door doesnt support public trackers. You can enabled it here:
https://github.com/Cloudbox/Cloudbox/wiki/FAQ#enable-access-to-public-torrent-trackers

**Comment by desimaniac** [comment]
Next version of CB will have a settings option that you could use to toggle this on or off.
