### ISSUE TITLE
Setting to disable Auth for Portainer

### ISSUE THREAD

**Issue by JigSawFr** [Cloudbox/Cloudbox#350]
Is it possible to edit ansible role of portainer to permit lunch of portainer without auth support ?
It can be great in case of authentication handled by Nginx Proxy / Organizr.
Maybe by adding a setting value to settings / adv-settings ?
Thank you

PS: Maybe something similar to rutorrent too instead of editing embedded nginx container.

**Comment by desimaniac** [comment]
Portainer does not get installed with auth enabled OOB. You do that during setup.

**Comment by desimaniac** [comment]
I realized theirs is a command flag as well. I’ll include it in a setting form somehow.

**Comment by JigSawFr** [comment]
> I realized there’s a command flag as well. I’ll include it in a setting form somehow.

Oh yeah i missed to speak about it but in my mind i was referring to it ;)

@desimaniac is-it possible to move authentication of rutorrent to nginx-proxy ? Because at this step, ruttorent htpasswd is enforced in rutorrent container and re-built each time an upgrade is done. (So, unable to remove authentication definitely)

Thank you ;)

**Comment by desimaniac** [comment]
Yeah I’ll figure out something for it. If I leave an issue/feature request open, it’s usually because I’m considering it or planning on adding it in some form.

**Comment by saltydk** [comment]
Portainer versions above 2.0 will no longer support no auth. https://github.com/portainer/portainer/issues/4305
