### ISSUE TITLE
Fill "_custom" config of roles

### ISSUE THREAD

**Issue by JigSawFr** [Cloudbox/Cloudbox#354]
Hi guys,
Just wanted to add another volume on plex docker container,
I've taken a look in Plex role, especially in main.yml and seen that there is a "plex_docker_volumes_custom: []" field.
How can in set my volume in it ? Without loosing it after updating local cloudbox branch :)
Via adv_settings ? settings ?
Thank you !

**Comment by After-Shock** [comment]
Sent you a DM on discord, check there and see if that helps.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by desimaniac** [comment]
That's a dev
