### ISSUE TITLE
Work in progress - having trouble with setup page.

### ISSUE THREAD

**Issue by TheGadge** [Cloudbox/Cloudbox#356]
I do understand it's a work in progress, but would really appreciate help with the initial 'plex configuration' part of the setup guide.

Username and password is not shown in the current setup guide in the screenshot.
I've done port etc to the letter. I presume the username and password is the normal plex one as in the first setup login? I get a fail every time. I have the server I want selected (seedbox, not my nas).

Many thanks.
Will.

**Comment by saltydk** [comment]
Plex login is your plex.tv credentials.

**Comment by TheGadge** [comment]
> Plex login is your plex.tv credentials.

Tried that. Still failed. I logged out of plex to double-check credentials.

**Comment by RXWatcher** [comment]
Please join us on the discord server so we can actively help you.
-Rx
