### ISSUE TITLE
Downloading into the unionfs mount - fixing it properly

### ISSUE THREAD

**Issue by kultigspritzig** [Cloudbox/Cloudbox#360]
**Describe the problem**
By mounting `/mnt/local/downloads` and `/mnt/unionfs/unionfs` separately we cause Radarr to copy files instead of moving/hardlinking them. This is well documented (https://github.com/Cloudbox/Cloudbox/wiki/Downloading-into-the-unionfs-mount) and the solution suggested but advised against is to download directly to unionfs.

**Describe any solutions you think might work**
This can be properly fixed by modifying Radarr docker image to mount `/mnt/local`, `/mnt/remote` and `/mnt/downloads` together as one volume and re-create the `/mnt/unionfs` _internally_ inside the docker container, so that Radarr has access to a complete media set but moving the files around from downloads  happens in the same filesystem.

The  hotio/jackett image can still be used, but the dockerfile needs to be patched and the image build locally.

**Comment by saltydk** [comment]
You don't need to change the radarr docker at all. You can just remote path map /mnt/local to /mnt/unionfs in sonarr/radarr.

**Comment by ferensz** [comment]
[There's](https://github.com/Cloudbox/Community/wiki/Hardlinking-Guide) a wiki entry on the Cloudbox community repo about the hardlinking.

**Comment by kultigspritzig** [comment]
Thanks. I think that both of these wiki pages should be combined as they ultimately serve the same purpose – to reduce the I/O and disk space used.

**Comment by MollyBe** [comment]
I download nzbs/torrents directly into their own MergerFS mount. The warning is only for torrents and warns that the mount may crash. I haven't had that happen, I can't say whether it's because I use a different mount or if it's something else.

**Comment by saltydk** [comment]
I believe the warning was for unionfs and not mergerfs.
