### ISSUE TITLE
Install fails due to docker-py dependency ssl_match_hostname (ubuntu 19.10)

### ISSUE THREAD

**Issue by elliots** [Cloudbox/Cloudbox#363]
**Describe the bug**
TASK [docker : Create cloudbox network] *************************************************************************************
Monday 16 March 2020  14:07:55 +0200 (0:00:00.021)       0:10:38.931 **********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named ssl_match_hostname. Try `pip install docker-py`"}

PLAY RECAP ******************************************************************************************************************
localhost                  : ok=356  changed=119  unreachable=0    failed=1

**To Reproduce**
Install

**System Information**

 - Cloudbox Version: Master
 - Operating System: Ubuntu Server 19.10
 - Linux Kernel: Linux version 5.3.0-26-generic (buildd@lgw01-amd64-013) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019

**Additional context**

Fixed by running `sudo apt install python-backports.ssl-match-hostname`

**Comment by RXWatcher** [comment]
We don't support that version of Ubuntu...Only LTS versions. 16.04 and
18.04 would have been fine.
