### ISSUE TITLE
Help with linking Sonarr & Radarr in Bazarr

### ISSUE THREAD

**Issue by waltuy** [Cloudbox/Cloudbox#365]
Hi,

I am trying to setup Bazarr, can someone please guide me on how to add Sonarr & Radarr to Bazarr.

Please refer this screenshot: https://i.ibb.co/804bH4D/Capture.jpg

Thanks in advance.

**Comment by hawkash** [comment]
#### Sonarr
- hostname  : **sonarr**
- Listening Port : **8989**
- base url : blank
- ssl enabled : no
- api key : copied from sonarr
<hr>

#### Radarr
- hostname  : **radarr**
- Listening Port : **7878**
- base url : blank
- ssl enabled : no
- api key : copied from radarr

**Comment by waltuy** [comment]
@hawkash , appreciate your response, it worked. Thank you.
