### ISSUE TITLE
Guide to Install OpenVPN Server

### ISSUE THREAD

**Issue by waltuy** [Cloudbox/Cloudbox#366]
I am trying to install OpenVPN server on my Cloudbox server from here: [https://hub.docker.com/r/kylemanna/openvpn/](url)

I am following this tutorial but no luck: [https://github.com/Cloudbox/Cloudbox/wiki/Add-Your-Own-Docker-Container-Into-Cloudbox](url)

Can someone please help with steps to successfully install it on Cloudbox.

Thanks in advance.

**Comment by saltydk** [comment]
The wiki you linked to tells you everything you should know to adapt a docker into the Cloudbox network. If you want help here you will need to be more specific regarding what you have tried so far, like actual examples. Otherwise you should join the discord instead of writing here.

**Comment by waltuy** [comment]
I followed the below commands and openvpn container is showing as running in portainer but what should I do next.? how do I access the openvpn .ovpn file.? Thanks for help.

`docker run -d \
    --name openvpn \
    --restart=always \
    -e PGID=1000 -e PUID=1000 \
    --network=cloudbox \
    --network-alias=openvpn \
    -v /opt/openvpn/:/config \
    -v /mnt/:/mnt/ \
    --label com.github.cloudbox.cloudbox_managed=true \
    -e VIRTUAL_PORT=1194 \
    -e VIRTUAL_HOST=openvpn.mydomain.com \
    -e LETSENCRYPT_HOST=openvpn.mydomain.com \
    -e LETSENCRYPT_EMAIL=me@myemail.com \
    kylemanna/openvpn`

**Comment by saltydk** [comment]
https://github.com/kylemanna/docker-openvpn

**Comment by mvthul** [comment]
I find OpenVPN access server with gui more friendly
docker run -d \
  --name=openvpn-as \
  --cap-add=NET_ADMIN \
  -e PUID=1000 \
  -e PGID=1000 \
  -v /opt/openvpn-as:/config \
  --network=cloudbox \
  --network-alias=vpn  \
  --label com.github.cloudbox.cloudbox_managed=true \
  -e VIRTUAL_HOST=Test.domain.com  \
  -e VIRTUAL_PORT=943  \
  -e UPSTREAM_NAME=test \
  -e LETSENCRYPT_HOST=test.domain.com \
  -e LETSENCRYPT_EMAIL=Test@gmail.com  \
  -e TZ=Europe/Amsterdam \
  -e INTERFACE=eth0 \
  -p 943:943 \
  -p 9443:9443 \
  -p 1194:1194/udp \
  --restart unless-stopped \
  linuxserver/openvpn-as
