### ISSUE TITLE
Sonarr Not installing

### ISSUE THREAD

**Issue by christcb03** [Cloudbox/Cloudbox#375]
**Describe the bug**
After attempting to update to the latest cloudbox code and running the installer Sonarr is missing. The container is not present and I get the error below.

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image hotio/sonarr3:latest - 404 Client Error: Not Found (\"pull access denied for hotio/sonarr3, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\")"}

**To Reproduce**
1. Update repo "cd ~/cloudbox && git fetch && git reset --hard @{u}"
2. run "sudo ansible-playbook cloudbox.yml --tags cloudbox"
3. See error near end of output from playbook

**Expected behavior**
Clean install

**Logs**
What logs should I look at?

If issue occurs during Ansible playbook, run playbook with `-vv` to output detailed debug log.

**System Information**

 - Cloudbox Version:  1.4.5, Master (latest)
 - Operating System: Ubuntu 16.04.6 LTS
 - Linux Kernel: 4.15.0-91-generic
**Additional context**

**Comment by owine** [comment]
You need to update your repo. Please follow https://github.com/Cloudbox/Cloudbox/wiki/Updating-Cloudbox#update-cloudbox to update your Cloudbox repo and run the Sonarr tag/role again. The docker image used for Somarr changed a while back and a repo update is required to pick up the new one.

**Comment by christcb03** [comment]
That was my first step... does not not do that?

Update repo "cd ~/cloudbox && git fetch && git reset --hard @{u}"

**Comment by owine** [comment]
Give it another try. You can also use `git status` after the `git fetch` to see if you are up to date with master. Sometimes an additional reset is needed.

**Comment by christcb03** [comment]
Ohh hmm I am somehow on a different repo.... I remember trying this but not how to change it back.

Your branch is up-to-date with 'origin/feature/varken'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        roles/plex/defaults/main.yml.save
        roles/plex/defaults/main.yml.save.1

**Comment by owine** [comment]
`git checkout master` should get you back on master. That’s why it seemed like the update wouldn’t take. I’d suggest running the full `cloudbox` / `feederbox` / `mediabox` tag to catch any changes.

**Comment by christcb03** [comment]
Yup, that sure did it. Thank you so much for the quick response!!  You guys are AWESOME for putting this together. Best and easiest way to setup a seedbox I've ever seen!
