### ISSUE TITLE
Make the external IP detection method configurable

### ISSUE THREAD

**Issue by juchong** [Cloudbox/Cloudbox#376]
---

**Describe the problem**
I'm running pfSense as my main router (unbound for DNS Resolution) along with HAProxy for SSL offloading. I ran into an issue where the Cloudbox install didn't properly detect my external IP and instead returned the IP of the upstream DNS server used for resolution. 

**Describe any solutions you think might work**
I was able to work around the issue by using an HTTP call (curl) to determine my external IP rather than using `dig`. Adding a configuration option in adv_config would make it easier to work around connectivity issues if the user's DNS is somehow being NAT'd upstream by the gateway. 

`File: cloudflare-dns/tasks/main.yml`

`#shell: dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'\"$`
`shell: curl -s http://whatismyip.akamai.com/`

**Additional context**
This is an easy problem to work around, so definitely not a priority. If this request isn't worthy of a configuration parameter, I can write something up on the Wiki as well.

**Comment by desimaniac** [comment]
It will be in the next version. Change has already been made in development branches.

**Comment by saltydk** [comment]
Closing this as it is already in the develop branch.
