### ISSUE TITLE
plex_autoscans auth issue?

### ISSUE THREAD

**Issue by jlim0930** [Cloudbox/Cloudbox#377]
I followed the instructions on https://github.com/Cloudbox/Cloudbox/wiki/Install:-Plex-Autoscan.  I have a cloudbox instance and not a separate one.  The token was added automatically since the information was added to accounts.yml during the install.

Whenever plex_autoscan runs I keep getting the following in my logs:

'''
Mar 30 11:08:52 u18cry scan.py[1040]:  2020-03-30 11:08:52,454 -    ERROR -      PLEX [140649882564352]: Exception checking if Plex was available at https://plex.domain.com:
Mar 30 11:08:52 u18cry scan.py[1040]: Traceback (most recent call last):
Mar 30 11:08:52 u18cry scan.py[1040]:   File "/opt/plex_autoscan/plex.py", line 608, in wait_plex_alive
Mar 30 11:08:52 u18cry scan.py[1040]:     timeout=30, verify=False)
Mar 30 11:08:52 u18cry scan.py[1040]:   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
Mar 30 11:08:52 u18cry scan.py[1040]:     return request('get', url, params=params, **kwargs)
Mar 30 11:08:52 u18cry scan.py[1040]:   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
Mar 30 11:08:52 u18cry scan.py[1040]:     return session.request(method=method, url=url, **kwargs)
Mar 30 11:08:52 u18cry scan.py[1040]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
Mar 30 11:08:52 u18cry scan.py[1040]:     resp = self.send(prep, **send_kwargs)
Mar 30 11:08:52 u18cry scan.py[1040]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
Mar 30 11:08:52 u18cry scan.py[1040]:     r = adapter.send(request, **kwargs)
Mar 30 11:08:52 u18cry scan.py[1040]:   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
Mar 30 11:08:52 u18cry scan.py[1040]:     raise ConnectionError(e, request=request)
Mar 30 11:08:52 u18cry scan.py[1040]: ConnectionError: HTTPSConnectionPool(host='plex.domain.com', port=443): Max retries exceeded with url: /myplex/account (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb997c0910>: Failed to establish a new connection: [Errno 111] Connection refused',))
Mar 30 11:08:52 u18cry scan.py[1040]:  2020-03-30 11:08:52,455 -  WARNING -      PLEX [140649882564352]: Checking again in 15 seconds (attempt 31)...
Mar 30 11:09:07 u18cry scan.py[1040]:  2020-03-30 11:09:07,499 -    ERROR -      PLEX [140649882564352]: Exception checking if Plex was available at https://plex.domain.com:
'''

so it seems like an auth issue.

I looked in /opt/plex_autoscan/config/config.json and saw the following
'''
   "PLEX_USER":"plex",
   "PLEX_TOKEN":"aaaa",
'''

shouldn't the username be my username for plex?

Lastly I did match up the token with the output from
sudo ansible-playbook cloudbox.yml --tags plex_auth_token and /opt/scripts/plex/plex_token.sh

and they do match.

however when I grep for PlexOnlineToken from Preferences.xml from plex it gives me a different token.

so are the 2 settings above correct or will this be some other issue?

Lastly when I goto the url provided by /opt/scripts/plex_autoscan/plex_autoscan_url.sh

i get unauthorized access message

**Comment by saltydk** [comment]
PLEX_USER is the user account (linux) that is running Plex. In the case of Cloudbox that user is called plex. If you have entered the correct login details in your accounts.yml and it is still pulling the wrong token, could it be that you have more than one server attached to your account? At any rate you can manually enter the correct token that you found into the config.

**Comment by jlim0930** [comment]
so if i have multiple plex servers running the token that I have might be from the other plex server?

I ran 
TOKEN=`cat "/path/to/Preferences.xml" | sed -e 's;^.* PlexOnlineToken=";;' | sed -e 's;".*$;;' | tail -1`
echo $TOKEN
on both the other plex server and the one on cloudbox install and I am getting different values than what was in my plex_autoscan

but you are stating that the plex on the cloudbox instance should match the TOKEN i get back from it correct?

**Comment by jlim0930** [comment]
so for a test I used the token from the local cloudbox instance and plex_autoscan did not error out and picked up the files.

Thanks for the help!
