### ISSUE TITLE
Wiki misleading about rutorrent download location

### ISSUE THREAD

**Issue by kultigspritzig** [Cloudbox/Cloudbox#380]
The https://github.com/Cloudbox/Cloudbox/wiki/Basics:-Cloudbox-Paths#a1 implies that 
> ruTorrent downloads into /downloads/torrents/rutorrent/incoming/ and moves completed downloads to /downloads/torrents/rutorrent/completed/

, which is no longer the case as all torrents go to "completed" now.

**Comment by desimaniac** [comment]
Updated. Thanks.
