### ISSUE TITLE
Plex docker doesn't autoupdate on startup

### ISSUE THREAD

**Issue by kultigspritzig** [Cloudbox/Cloudbox#386]
**Describe the bug**
Plex container never updates on restarting, despite what the documentation says. I checked and the `version.txt` file contains the same version as currently installed, so when the `/etc/cont-init.d/50-plex-update` script  runs the code below, it just exits with error code 0 before it even gets to checking the current version online: 

```
# Short-circuit test of version before remote check to see if it's already installed.
if [ "${versionToInstall}" = "${installedVersion}" ]; then
  exit 0
fi
```

**Expected behavior**
Plex should automatically update to latest upon restarting
 - Cloudbox Version: master
 - Operating System: Ubuntu Server 16.04 LTS
 - Linux Kernel: 4.15

**Additional context**
The upstream had some changes recently that could potentially fix this:
https://github.com/plexinc/pms-docker/commit/4d069dc46541f535a6d40fb4e26744fd69060bac#diff-e82a0871da59ae8d39491183198d8f8e

**Comment by kultigspritzig** [comment]
I can see that the https://github.com/Cloudbox/Cloudbox/wiki/Updating-Cloudbox-Apps/19842a74ee0868e085dd364502d4cc416a9c8911 was updated 10 days ago and the means of updating Plex was changed to "Ansible tag". Was this on purpose or just to reflect that the current in-container updating mechanism is broken?

**Comment by saltydk** [comment]
The update feature of the Plex docker image is not broken. It depends entirely on what tag you are running. If you had read the front page of the github you linked you would have gotten your answer.

Beta and public are images that download Plex on startup, thus updating on restarts. The other tags are images that include the Plex binary and does not update until you update the image itself.

**Comment by kultigspritzig** [comment]
> If you had read the front page of the github you linked you would have gotten your answer.

Or you could avoid being patronizing and instead say "Yes, the wiki was _misleading_ since the default plex docker image tag we use is for a version that does not automatically update upon container restart."

**Comment by saltydk** [comment]
I do apologize for coming across as patronizing. I should not have assumed lazy behavior. The wiki is struggling as far as being kept up to date since quite a few things have been updated so things slip through the cracks and I just assumed people knew. My bad :)

**Comment by kultigspritzig** [comment]
I appreciate your response. I should have also checked the actual tag of the docker image on my end, just assumed it had been the stable one. Either way, thanks for explaining.

**Comment by shapetheLOLa** [comment]
I'm not sure what to do here. I just started using cloudbox yesterday, with plex. Plex is on an old version and not updating when restarting. Im on the master branch of cloudbox and didn't change a setting there. What do I need to do to get the latest plex version running?
