### ISSUE TITLE
Hostess Appears to be Non Functioning

### ISSUE THREAD

**Issue by qbattersby** [Cloudbox/Cloudbox#388]
**Describe the bug**
When running hostess from CLI it spits out this error. Note This is not my username being shown etc so something definitely amiss here. (Appears to be hostess dev's 

**To Reproduce**
1. Run hostess from CLI

**Expected behavior**
Hostess runs.

**Error**
`panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
main.wrappedMain(0xc00010a010, 0x1, 0x1, 0x0, 0xc000094058)
	/Users/cbednarski/code/hostess/main.go:78 +0xd5b
main.main()
	/Users/cbednarski/code/hostess/main.go:147 +0x45`

**System Information**

 - Cloudbox Version: Master, Latest
 - Operating System: Ubuntu Server 18.04 LTS
 - Linux Kernel: 4.17.0-041700-generic

**Comment by saltydk** [comment]
You need to report this to the developer of hostess. Remember to include more information like the version of golang and version of hostess.

**Comment by saltydk** [comment]
On second thought, did you run hostess as root / sudo?

**Comment by qbattersby** [comment]
Yes attempted as sudo as well.

**Comment by chazlarson** [comment]
The error is showing the source file where the error happens.  The path is the path at the time of building the app.  If you built it in the same way and I ran it and got the error I’d see your username.  That portion is not unexpected.

**Comment by qbattersby** [comment]
Hmm it seems this only fails when direct running the command: hostess which is supposed to output the help screen. Running the command hostess -h works.
I supposed this should be closed.
