### ISSUE TITLE
Sickbeard MP4 automator not able to be used in Sonarr

### ISSUE THREAD

**Issue by s3638844** [Cloudbox/Cloudbox#389]
**Describe the bug**
Fails to be added to Sonarr Connections

**To Reproduce**
Attempt to add SBA as per wiki, fails when trying to add to Sonarr.

**Expected behavior**
following instructionns on wiki for enabling SBA for Sonarr (v3, not v2).  Fails when test or save when should apply successfully like it did with Radarr (v2, not v3)

**Logs**
Link to debug or trace log files.
https://pastebin.com/u4w0kBxk

**System Information**

 - Cloudbox Version:Master (latest)
 - Operating System: Ubuntu Server 18.04 LTS
 - Linux Kernel: 4.15.0-99-generic

**Comment by saltydk** [comment]
Log is saying that you are missing the python module called requests.

**Comment by s3638844** [comment]
Suggest I pip install inside the sonarr container? Added as expected to radarr so I presume it’s the docket container missing it.  Do you know if it’s pip or pip3?
