### ISSUE TITLE
Portainer : Failure  / Unable to connect to the Docker endpoint

### ISSUE THREAD

**Issue by GautierT** [Cloudbox/Cloudbox#391]
**Describe the bug**
"Failure  / Unable to connect to the Docker endpoint" error when clicking on the local group.

**To Reproduce**
1. Install portainer with `sudo ansible-playbook cloudbox.yml --tags portainer`
2. Follow https://github.com/Cloudbox/Cloudbox/wiki/Install:-Portainer
3. Go to `portainer.domain_name.com`
4. Click on the local group. See error toast : `Failure  / Unable to connect to the Docker endpoint`

**Screenshots**
<img width="873" alt="Capture d’écran 2020-05-07 à 14 27 55" src="https://user-images.githubusercontent.com/6089653/81294634-77914480-906f-11ea-99d0-ec153644a69a.png">

**Logs**
Nothing relevant in the `docker logs -f portainer` 

**System Information**

 - Cloudbox Version: Develop (latest)
 - Operating System: [e.g. Ubuntu Server 16.04 LTS]

**Additional context**

Thanks !

**Comment by saltydk** [comment]
Have you tried deleting /opt/portainer/ and rerunning the tag?

**Comment by GautierT** [comment]
Yes. 2 times. :/
