### ISSUE TITLE
Allow the use of a restricted Cloudflare API Token rather than a Global API Key

### ISSUE THREAD

**Issue by matchai** [Cloudbox/Cloudbox#392]
**Describe the problem**
Users are being encouraged to provide a Global API Key with global access to their accounts. If this token gets in the wrong hands, this key allows anyone to read and edit _any_ data or settings on a Cloudflare account.

**Describe any solutions you think might work**
Cloudflare allows the creation of restricted API Tokens, which can be quickly made to only have access to edit DNS entries on a specific Cloudflare Zone.

**Additional context**
An example of the steps needed to generate an API Token able to edit DNS entries:

![image](https://user-images.githubusercontent.com/4658208/81733845-a4bf6780-9460-11ea-94bc-1495a3d36c09.png)

![image](https://user-images.githubusercontent.com/4658208/81733915-b99bfb00-9460-11ea-8631-eef0affb88c8.png)

![image](https://user-images.githubusercontent.com/4658208/81734061-f36d0180-9460-11ea-9045-9f615a613b48.png)

![image](https://user-images.githubusercontent.com/4658208/81734158-17304780-9461-11ea-88ca-f5169f862b2f.png)

![image](https://user-images.githubusercontent.com/4658208/81734249-3b8c2400-9461-11ea-9f73-dc8c5b776591.png)

**Comment by owine** [comment]
Have you tried this by chance? Cloudbox uses the Ansible module for Cloudflare DNS (https://docs.ansible.com/ansible/latest/modules/cloudflare_dns_module.html) and while the docs suggest the Global API Key is what is needed, they do use the Token terminology.

If it does not work, I would suggest upstreaming this request for inclusion in the Ansible module.
