### ISSUE TITLE
rclone_vfs stops working.

### ISSUE THREAD

**Issue by C42EFF4Lbb54dwg** [Cloudbox/Cloudbox#394]
As the title says, on a clean and up to date install, it randomly changes to exit (inactive) after a few hours with nothing in the logs. The consequences include certain items becoming unavailable on Plex. 

Changing the systemd service from "on-abort" to "always" resolves the issue (after reloading the daemon and restarting the service).

**Comment by RXWatcher** [comment]
What is the message when the mount dies? You might need to up the rclone log level on it to capture it. I've left mine for a month or more without issue before so I think you should resolve the actual issue of why the mount dies and not work around it with this change.

**Comment by saltydk** [comment]
Given the encryption issue he just posted I would assume he is not using a default clean install. As RX is saying it is hard to respond in any useful manner without logs to go through. You will have more luck asking for help on our discord.
