### ISSUE TITLE
Use hardlinking by design

### ISSUE THREAD

**Issue by sevospl** [Cloudbox/Cloudbox#395]
By design, CloudBox's pattern for settings.yml assumes that everything is supposed to be downloaded to `/mnt/local/downloads/torrents` or `/mnt/local/downloads/nzbs` which - in my opinion - doesn't make any sense as unionfs is used all the time. Because of this, nothing can be hardlinked as Sonarr and Radarr are pointed (according to the wiki) to `/mnt/unionfs/Media...`. An issue of so called "cross-linked devices" occurs in this very case scenario.

What does it mean? You encourage people to copy all the time which means a waste of I/O and slows down the entire hard drive (assuming it's a traditional hard drive). It also means slower importing and less perfomance for downloading/uploading itself.

So what I would suggest is to change a few things:

- The default [settings.yml.default](https://github.com/Cloudbox/Cloudbox/blob/master/defaults/settings.yml.default) pattern should have downloads pointed to locations like this:
```
downloads:
  nzbs: /mnt/unionfs/downloads/nzbs
  torrents: /mnt/unionfs/downloads/torrents
```
- Remote mappings should be enforced to like this:
![image](https://user-images.githubusercontent.com/15851064/82130794-e8063700-97ce-11ea-99e2-453438004caa.png)
- [Radarr](https://github.com/Cloudbox/Cloudbox/wiki/Install%3A-Radarr), [Sonarr](https://github.com/Cloudbox/Cloudbox/wiki/Install%3A-Sonarr) and [Lidarr](https://github.com/Cloudbox/Cloudbox/wiki/Install%3A-Lidarr) guides should start encouraging people to hardlink.

Hint: if someone sees it and want to have their current set up to be changed to start hardlinking, don't forget to rerun a tag (sonarr, radarr and rutorrent) once `settings.yml` changed, otherwise an old way of mounting /downloads remains.

**Comment by saltydk** [comment]
Editing settings.yml assumes everyone will use mergerfs and not caring about the performance penalty (downloading directly to unionfs). Nothing prevents users from using sonarr/radarr hardlinking with the default setup as you suggest with remote path mappings (with no meaningful penalty). If you want the wiki to change by all means make the edit you want to see in the world.
