### ISSUE TITLE
Local Plex installation always remote for local devices

### ISSUE THREAD

**Issue by dmeuwissen** [Cloudbox/Cloudbox#399]
I am running Cloudbox on my local server but Plex is streaming over the internet instead of over LAN. The Plex server is also showing "Remote". I have tried to set the open ports property in the "advanced_settings.yml" and now I can use the server IP to get local access but when using the plex website I get the same issue as before.

**Comment by saltydk** [comment]
You will always have traffic show as remote even if you were streaming it over LAN when using a docker network like Cloudbox uses.

**Comment by damusmf** [comment]
I see this is an old thread but still open. However, that is not true.  My local streams show as the nginx docker IP and not the WAN IP or the actual local LAN IP address.  Been happening for months and is annoying but i don't think it is harming anything.
