### ISSUE TITLE
Tautulli and Varus reporting Plex streams as insecure.

### ISSUE THREAD

**Issue by dipstick1987** [Cloudbox/Cloudbox#402]
According to Tautulli or the Varys iOS app all of the streams from CB are reporting as insecure which I believe means the streams are happening via HTTP.

My understanding of the system is that the Proxy/Plex Server are setup out of the box to support http streams to enable older devices without https support to work. The issue with this is security and privacy. 

I feel there should be an option or configuration setting for users that wish to force secure (https) streaming only and are willing to forego legacy device support. To my knowledge there is nothing on the wiki about this.

**Comment by saltydk** [comment]
I'm don't think the default configuration (as of develop branch anyway) allows http traffic out of the box. Unless you open port 32400 in the docker container it should only allow encrypted traffic since the default nginx config redirects port 80 traffic to https.

**Comment by owine** [comment]
Plex doesn’t know about/recognize the reverse proxy so it thinks everything is unsecured HTTP. As all traffic passes through the proxy it is in fact HTTPS.
