### ISSUE TITLE
Upgrade ansible version from 2.5 to 2.9

### ISSUE THREAD

**Issue by addbee** [Cloudbox/Cloudbox#403]
---

**Describe the problem**
I'm working on some streamlined ansible tasks for the various community roles, and wanted to make use of `docker_container_info` (to skip a task if a container is already running - shared databases) but this is only available in ansible > 2.8

**Describe any solutions you think might work**
Update installer to pin a higher ansible version

**Additional context**
I've run `pip install --upgrade ansible` to go to 2.9.9 on my dev server, and haven't had any problems so far, but it was only recently done, so I'll keep you posted if i notice anything.

**Comment by saltydk** [comment]
Dev branch already runs with 2.9.4

**Comment by addbee** [comment]
Great - looking forward to the next release then.
