### ISSUE TITLE
Installing dependencies utilizes Python-Pip package, which has been removed from Ubuntu 20.04

### ISSUE THREAD

**Issue by oosena** [Cloudbox/Cloudbox#405]
**Describe the bug**
During the installation of dependencies, the installer fails because of a call for the python-pip package, which is no longer available on Ubuntu 20.04 because it utilizes Python3. pip3 should be utilized.

**To Reproduce**
1. Create Ubuntu 20.04 server
2. Install dependencies via curl -s https://cloudbox.works/scripts/dep.sh | sudo -H bash; curl -s https://cloudbox.works/scripts/repo.sh | bash >/dev/null 2>&1; cd ~/cloudbox
3. dependencies install fails

**Expected behavior**
The install should not fail, and should complete successfully

**Screenshots**
See logs below

**Logs**
ubuntu@cloudbox:~$ wget -qO- https://cloudbox.works/scripts/dep.sh | sudo -H bash; wget -qO- https://cloudbox.works/scripts/repo.sh | bash >/dev/null 2>&1; cd ~/cloudbox
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-31 linux-headers-5.4.0-31-generic linux-image-5.4.0-31-generic
  linux-modules-5.4.0-31-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/12.3 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 156025 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.0.2ubuntu0.1_all.deb ...
Unpacking apt-transport-https (2.0.2ubuntu0.1) over (2.0.2ubuntu0.1) ...
Preparing to unpack .../software-properties-common_0.98.9_all.deb ...
Unpacking software-properties-common (0.98.9) over (0.98.9) ...
Setting up apt-transport-https (2.0.2ubuntu0.1) ...
Setting up software-properties-common (0.98.9) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2) ...
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://iad-2.clouds.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://iad-2.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://iad-2.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
'main' distribution component is already enabled for all sources.
'universe' distribution component is already enabled for all sources.
'restricted' distribution component is already enabled for all sources.
'multiverse' distribution component is already enabled for all sources.
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://iad-2.clouds.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://iad-2.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://iad-2.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
_**Note, selecting 'python-dev-is-python2' instead of 'python-dev'
E: Unable to locate package python-pip
/usr/bin/python3: No module named pip
/usr/bin/python3: No module named pip
/usr/bin/python3: No module named pip
bash: line 94: python: command not found
bash: line 96: python: command not found
bash: line 98: python: command not found
cp: cannot stat '/usr/local/bin/pip': No such file or directory
cp: cannot stat '/usr/local/bin/pip3': No such file or directory**_

**System Information**
 - Cloudbox Version: Master (latest)
 - Operating System: Ubuntu Server 20.04
 - Linux Kernel: 5.4.0-37-generic

**Additional context**
None

**Comment by saltydk** [comment]
No work has been done to support 20.04 yet so this is not unexpected and our wiki clearly states which OS versions that are supported.
