### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by tulkarxxx** [Cloudbox/Cloudbox#407]
Hi, I have reinstalled 3 times today cloudbox, every time I try to access to apps using https I get certificate error, can not trust in certificate.
I installed cloudbox without issues 3 months ago, has something changed?

Best regards

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Link to debug or trace log files.

If issue occurs during Ansible playbook, run playbook with `-vv` to output detailed debug log.

**System Information**

 - Cloudbox Version: [e.g. 1.4.0, Master (latest), Develop (latest)]
 - Operating System: [e.g. Ubuntu Server 16.04 LTS]
 - Linux Kernel: [e.g. 4.15]

**Additional context**

**Comment by owine** [comment]
Check the logs for the letsencrypt docker container

`docker logs letsencrypt`

There are some other things to check/try here: https://github.com/Cloudbox/Cloudbox/wiki/FAQ#ssl-certificate-issues

Possibilities are failing HTTP challenge (Cloudflare proxy can cause issues with that) or Let’s Encrypt rate limits

**Comment by tulkarxxx** [comment]
Thanks , I will do it

**Comment by tulkarxxx** [comment]
Issue not related with certificates or bug, closing
