### ISSUE TITLE
Separate os / data disks

### ISSUE THREAD

**Issue by rogerlawrence79** [Cloudbox/Cloudbox#410]
I have 2 SSDs (240 / 1TB).  I'd like to move all the union, local data to the 1TB drive.  I've tried symlinking, but the plex docker isn't too fond of it.  I was able to specify the transcodes and nzb download locations in the settings yml... Can this be done?

**Comment by RXWatcher** [comment]
Union shouldnt matter as it's a union of local and remote. It doesnt actually contain any data.

Mount the 1TB drive as /mnt/local and you're good to go...so edit /etc/fstab to make this change.

**Comment by saltydk** [comment]
Just remember to rename the local folder you have already if it contains data you want to keep and move it over after following the above advice.

**Comment by rogerlawrence79** [comment]
Thank you! That worked like a charm...
