### ISSUE TITLE
Add mp3 bitrate analyses to audio codec scores

### ISSUE THREAD

**Issue by silkyclouds** [Cloudbox/Cloudbox#418]
Hi there,

I would like to use plex dupefinder to cleanup my music library. 
I currently do have several versions of albums (like, sometimes, literally 4 or 5 version. of an album) and would like to remove all the lower bitrate versions. 

I understand it is already possible in current state to score based on the files type mp3 (1000) vs. flac (2500). But is there any way to go a little further and to tell dupefinder to score the mp3/flac files based on their bitrate ? 

Example : 

mp3 128 kbit (100) 
mp3 192 kbit (200)
mp3 (V0) (1000)
flac 16bit (2000)
flac 24 bit (3000)

this would help me a lot and I'm pretty sure other users would take benefit of this. 

Can you please let me know if this is feasible ? As plexamp now allows to display the bitrate, I guess this information is stored somewhere in the plex library database. 

Thanks !

**Comment by saltydk** [comment]
You'll want to open an issue on the repository for Plex Dupefinder https://github.com/l3uddz/plex_dupefinder
