### ISSUE TITLE
Plex transcode error

### ISSUE THREAD

**Issue by liamarmitage** [Cloudbox/Cloudbox#420]
**Describe the bug**
All content no longer transcodes and constant error in logs and on plex client.

I have deleted plex container and image, reinstalled using cloudbox tags and still get the error.

**To Reproduce**
1. Try and play content

**Expected behavior**
Content plays

**Screenshots**
N/A

**Logs**
Logs attached

If issue occurs during Ansible playbook, run playbook with `-vv` to output detailed debug log.

**System Information**

 - Cloudbox Version: Master (Latest)
 - Operating System: Ubuntu 18.04.5 LTS
 - Linux Kernel: Linux version 4.15.0-115-generic
[Plex Media Server.log](https://github.com/Cloudbox/Cloudbox/files/5185187/Plex.Media.Server.log)
[com.plexapp.system.log](https://github.com/Cloudbox/Cloudbox/files/5185188/com.plexapp.system.log)

**Additional context**

**Comment by saltydk** [comment]
Guessing ```Sep 08, 2020 00:27:48.210 [0x7f08457fa700] ERROR - [FFMPEG] - libva: /usr/lib/plexmediaserver/lib/dri/iHD_drv_video.so init failed``` May point you to solving your problem. Without system specific information you are on your own.

**Comment by liamarmitage** [comment]
> Guessing `Sep 08, 2020 00:27:48.210 [0x7f08457fa700] ERROR - [FFMPEG] - libva: /usr/lib/plexmediaserver/lib/dri/iHD_drv_video.so init failed` May point you to solving your problem. Without system specific information you are on your own.

Thanks for the reply.. i have researched this and tried various things (remove driver etc) but i still get an error. This was working up until i updated ubuntu funny enough..

I am using an Hetzner server, Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06) 256M],

**Comment by saltydk** [comment]
What have you set in your adv_settings.yml in regards to the gpu?

**Comment by liamarmitage** [comment]
> What have you set in your adv_settings.yml in regards to the gpu?

gpu: 
  intel: yes
  nvidia: 
    enabled: no
    driver: 418.30

**Comment by saltydk** [comment]
What does this return
```docker inspect -f '{{ .Mounts }}' plex```

**Comment by liamarmitage** [comment]
> What does this return
> `docker inspect -f '{{ .Mounts }}' plex`

[{bind  /mnt /mnt  rw true rprivate} {bind  /dev/shm /dev/shm  rw true rprivate} {bind  /opt/scripts /scripts  rw true rprivate} {bind  /etc/localtime /etc/localtime  ro false rprivate} {bind  /mnt/unionfs/Media /data  rw true rprivate} {bind  /tmp /tmp  rw true rprivate} {bind  /mnt/local/transcodes/plex /transcode  rw true rprivate} {bind  /opt/plex /config  rw true rprivate}]

**Comment by saltydk** [comment]
We can probably solve this faster if you poke me on our discord. Do you have discord?

**Comment by liamarmitage** [comment]
> We can probably solve this faster if you poke me on our discord. Do you have discord?

yeah... not sure on url for discord mind

**Comment by saltydk** [comment]
https://discord.io/cloudbox

**Comment by liamarmitage** [comment]
> https://discord.io/cloudbox

Ive opened the channel but can't find you :-( i am called chinchachee if you can PM me?
