### ISSUE TITLE
Organizr V2

### ISSUE THREAD

**Issue by MarkProjectRepo** [Cloudbox/Cloudbox#442]
The organizr image is no longer compatible and will no longer load. Either the version needs to be pinned to v1, or the images need to be changed for V2.

![image](https://user-images.githubusercontent.com/7595234/102557944-58917100-409a-11eb-9371-b9972b3028cd.png)

**Comment by saltydk** [comment]
I've just done a fresh install and v2 works fine. Would suggest you either haven't updated to the latest version on the repo or that you need to migrate your own install.

We already have a v1 version in a different role. Closing this. Go to the discord if you need support for the role as it is not broken as far as the install goes.
