### ISSUE TITLE
Setting to disable ruTorrent auth (persistent)

### ISSUE THREAD

**Issue by keldian** [Cloudbox/Cloudbox#443]
---

**Describe the problem**

You can disable ruTorrent auth by commenting out the `auth_basic` line or editing it to `auth_basic off;` in `/opt/rutorrent/nginx/nginx.conf`, but this gets reset whenever you run the rutorrent or cloudbox tag.

**Describe any solutions you think might work**

Have a user setting to disable the default Cloudbox auth for ruTorrent, edit the role accordingly.

**Additional context**

Useful in case you have other security in place for the app (e.g. Organizr auth)

**Comment by owine** [comment]
You can pass a Authorization header to essentially get a multi-layer authentication. This protects the app itself in the event it were to somehow be directly exposed and layers something like Organizr auth on top of it without a dual prompt.

In `/opt/nginx-proxy/vhost.d/sub.domain.tld_location`
```
proxy_set_header Authorization "Basic <encodedtoken>";
proxy_pass_header Authorization;
```
Where `<encodedtoken>` is Base64 encoded `user:pass`. i.e. for `seed:seed` the token would be `c2VlZDpzZWVk`.

**Comment by saltydk** [comment]
After owine's advice in this thread I'm closing this. https://github.com/Cloudbox/Community/wiki/Organizr-Auth-for-Nginx-Proxy-Apps would be the goto for stuff like this and owine had a stab at improving it. If things still aren't clear feel free to ask for help on our discord and maybe we'll have further improvements made to the wiki.
