### ISSUE TITLE
Will ARM be supported?

### ISSUE THREAD

**Issue by C-Fu** [Cloudbox/Cloudbox#444]
Good day,

Something like this is very much needed, a one-stop solution so to speak. Are there any plans to make it Pi compatible?

**Comment by saltydk** [comment]
If someone submits a PR then sure but no plans as of yet. I have done no research into what making it compatible would entail.

**Comment by chazlarson** [comment]
I looked at this a little bit some time ago.  Possible hurdles:

1. Getting docker installed on my Pi 4 running Ubuntu was not straightforward.
2. It is unknown whether all the docker images that cloudbox installs are available for ARM
3. It is unknown whether all the system packages that cloudbox depends on are available for ARM.
4. Supporting something other than Ubuntu [say, Raspian] would add yet more incompatibilities and challenges.

**Comment by C-Fu** [comment]
@chazlarson it's pretty easy in my case.
1. curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
2. For this one I have no real solution, but can offer some clues.
 - linuxserver has tons of compatible ARM containers. Case in point: https://registry.hub.docker.com/r/linuxserver/plex/tags and Organizr https://registry.hub.docker.com/r/organizr/organizr
 - I've made a simple script that installs docker, docker-compose, nginx proxy manager, portainer and organizr. It's mainly for personal use, and pretty much my first (second? foray into bash scripting lol. Have a look https://github.com/C-Fu/pi-setup
3. I have no idea. But so far upon trying out personally (and manually) everything seems to be working, or at least everything that I need - rclone, docker, docker-compose, organizr/organizr, linuxserver/radarr, linuxserver/sonarr, linuxserver/lidarr, tautulli/tautulli, linuxserver/tautulli, linuxserver/jackett, linuxserver/ombi, hotio/overseerr, portainer/portainer-ce, linuxserver/qbittorrent, and a few others. 
4. I find that with linuxserver's containers, some/most of the bind/volume mounts are actually interoperable between x86 and ARM. Even tautulli works, both on RPi 3b/3b+ and 4.

**Comment by saltydk** [comment]
I'm not going to implement this at this time. While running dockers might be easy, as you say, implementing our particular setup with ansible might not be as clear cut and I don't see a big market for this yet. I don't have any relevant devices to test this on at any rate.

As Chaz stated this potentially adds another layer of complexity and I'm not sure I see a big enough upside.

**Comment by chazlarson** [comment]
Maybe it was docker-compose that was the problem.

PR = Pull Request

Cloudbox is more than just docker containers; there's stuff installed by the preinstall and dependencies scripts that aren't in docker containers; maybe all those things work fine on whatever distro on RPi, maybe not.

Even once all those things are solved, what are you left with?  A very low-powered device running a bunch of CPU-intensive things.  I certainly wouldn't want to run nzbget on a Pi with all disk I/O going through USB.  Plex would be direct-play only, and again with its database on USB browsing the UI would be painful, I expect.

What I see is a lot of work for a substandard experience that will generate a lot of support issues.
