### ISSUE TITLE
integrate flaresolverr

### ISSUE THREAD

**Issue by rmichelena** [Cloudbox/Cloudbox#446]
Jackett becomes more crippled every day by the use of cloudflare protection on the trackers/indexers

there's Flaresolverr to aid in that, and Jackett already has a setting to integrate it, and it's available as docker

**Comment by saltydk** [comment]
It is already in Community for those that want to use it. https://github.com/Cloudbox/Community/blob/master/roles/flaresolverr/tasks/main.yml
