### ISSUE TITLE
Feature Request: add nzb.su rename script and python3-lxml dependency

### ISSUE THREAD

**Issue by ak2k** [Cloudbox/Cloudbox#447]
---

**Describe the feature request**
For support for renaming WtFnZb releases, I would like to add support for this renaming script to nzbget: https://nzb.su/ghostrename.txt (together with it's required dependency on python3-lxml).

**Describe any solutions you think might work**
- Add https://nzb.su/ghostrename.txt to scripts directory with .py extension
- Install lxml for python3 via 'apk add --no-cache py3-lxml'

**Additional context**
- https://nzb.su/forumpost/4510

**Comment by chazlarson** [comment]
This is doable on an individual system by anyone who wants to add support for this script; I don't think we need to add yet another thing to maintain.

Moreover, that script has not worked for everyone who has tried it, which I think also argues against adding it.  It could become yet another source of support issues.

**Comment by saltydk** [comment]
Poke hotio if the more recent additions haven't already covered this. https://github.com/hotio/nzbget

**Comment by ak2k** [comment]
Thank you both!

Will reach out to hotio for the dependencies, in case not covered by last updates and he thinks worth adding.

> This is doable on an individual system by anyone who wants to add support for this script

If someone wanted to attach a script such that it was automatically run whenever the container was updated (as part of the Cloudbox process of running the associated app tag(s)), what would be the recommended way to do that?

Granted one could script and run manually explicitly after any tag-based updating, but I wondered if there were a better way worth recommending. Thank you in advance!

**Comment by saltydk** [comment]
It is already included https://github.com/hotio/nzbget/blob/103bc7c48aa22e97dc9486b3d6d73ce39272b91d/linux-amd64.Dockerfile#L5

https://github.com/hotio/nzbget/blob/release/root/app/scripts/WtFnZb-Renamer.py

Unless I am missing something?

**Comment by ak2k** [comment]
Excellent! I hadn't had the chance to check yet, and really appreciate the confirmation!

More generally (for the future), is there a recommended way for people to maintain their own similar tweaks that are compatible with the Cloudbox update process?

**Comment by saltydk** [comment]
Once the traefik branch gets merged into develop you can just place scripts in /opt/scripts/rolename/ when it comes to hotio containers and it'll run the .sh scripts present. https://github.com/Cloudbox/Cloudbox/blob/develop_python3/resources/tasks/hotio/cont-init.d/files/99-cont-init-script-runner.sh

If you want support on how to do it manually with master I'd suggest going to the discord as this isn't really where we handle support questions.
