### ISSUE TITLE
Hi, I don't want to use Google Drive, I want to use onedrive as a storage disk, is it possible?

### ISSUE THREAD

**Issue by brokenman1** [Cloudbox/Cloudbox#448]
---
Hi, I don't want to use Google Drive, I want to use onedrive as a storage disk, is it possible?

**Describe the problem**
A clear and concise description of the problem you're looking to solve.

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

**Additional context**

**Comment by chazlarson** [comment]
Yes, as noted in the wiki:

https://github.com/Cloudbox/Cloudbox/wiki/Prerequisites%3A-Cloud-Storage
