### ISSUE TITLE
problem when trying to install cloudbox dependency 

### ISSUE THREAD

**Issue by freedom1701** [Cloudbox/Cloudbox#449]
Hello
I am a novice
I'm on ubuntu
when i try to install the cloodbox dependency it gives me this error message

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tvla3mry/cryptography/

can you help me?
thank you

**Comment by chazlarson** [comment]
What version of ubuntu, what command are you running, what branch of cloudbox?  This error isn't something I can recall seeing before.

BTW, the Discord is a better place for this sort of thing.

**Comment by freedom1701** [comment]
thank you for your reply

ubuntu 18.04.5 LTS minimum

command uses:

curl -s https://cloudbox.works/scripts/dep.sh | sudo -H bash; curl -s https://cloudbox.works/scripts/repo.sh | bash >/dev/null 2>&1; cd ~/cloudbox

Master brach - Combined

thank you for your help

**Comment by owine** [comment]
I can confirm this on a fresh VPS running the scripts, however it appears the associated python module (cryptography) installs successfully regardless.

**Comment by freedom1701** [comment]
does this mean that I keep moving forward ignoring this error? thank you

**Comment by owine** [comment]
Keep moving forward and if there are any further errors the Discord might be a better place to help troubleshoot

**Comment by freedom1701** [comment]
great thank you for your answers

**Comment by freedom1701** [comment]
Hello,
by continuing my installation, when installing mediabox

Install: Mediabox (Master branch)

by typing this command the:

sudo ansible-playbook cloudbox.yml --tags mediabox

I get 1 error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: No JSON object could be decoded
failed: [localhost] (item = hastebin) => {"changed": false, "item": "hastebin", "module_stderr": "Traceback (most recent call last): \ n File \" / tmp / ansible_XXBgUq / ansible_module_npm.py \ ", line 291, in <module> \ n main () \ n File \" / tmp / ansible_XXBgUq / ansible_module_npm.py \ ", line 268, in main \ n installed, missing = npm.list () \ n File \ "/ tmp / ansible_XXBgUq / ansible_module_npm.py \", line 192, in list \ n data = json.loads (self.exec (cmd, True, False)) \ n File \ "/ usr / lib / python2.7 / json / init_.py \ ", line 339, in loads \ n return _default_decoder.decode (s) \ n File \" / usr / lib / python2.7 / json / decoder.py \ ", line 364 , in decode \ n obj, end = self.raw_decode (s, idx = _w (s, 0) .end ()) \ n File \ "/ usr / lib / python2.7 / json / decoder.py \", line 382, ​​in raw_decode \ n raise ValueError (\ "No JSON object could be decoded \") \ nValueError: No JSON object could be decoded \ n "," module_stdout ":" "," msg ":" MODULE FAILURE ", "rc": 1}


I do not understand ....

Thanks for your help ....

**Comment by saltydk** [comment]
unless it exited the script before completing you can ignore that error.
