### ISSUE TITLE
large xmlrpc.log 

### ISSUE THREAD

**Issue by Sibicle** [Cloudbox/Cloudbox#462]
**Describe the bug**
my server was running out of space, exploring through `ncdu` I found that `xmlrpc.log` was 1.4 Tb

**To Reproduce**
1. `cd /opt/rutorrent/log/rtorrent`
2. `ls -lah`

```
➜  rtorrent ls -lah
total 1.4T
drwxrwxr-x 2 seed seed 4.0K Oct  8  2019 .
drwxrwxr-x 6 seed seed 4.0K Apr 22 02:00 ..
-rwxrwxr-x 1 seed seed 291M Apr 22 15:22 execute.log
-rwxrwxr-x 1 seed seed  275 Oct  8  2019 rtorrent.log
-rwxrwxr-x 1 seed seed 1.4T Apr 22 15:22 xmlrpc.log
```

**Expected behavior**
I would hope that the logs would get rotated

**Screenshots**
![image](https://user-images.githubusercontent.com/4299422/115780622-9ec34d80-a376-11eb-92b4-885011f144ad.png)

**System Information**

 - Cloudbox Version: master (latest, 4/22/21)
 - Operating System: Ubuntu 18.04.5 LTS
 - Linux Kernel: Linux 4.15.0-142-generic x86_64

**Comment by saltydk** [comment]
What is in your ```/opt/rutorrent/log/logrotate.status```

**Comment by Sibicle** [comment]
```
➜  rtorrent cat /opt/rutorrent/log/logrotate.status
logrotate state -- version 2
"/var/log/acpid.log" 2021-4-4-2:0:0
"/config/log/nginx/access.log" 2021-4-18-2:0:0
"/config/log/nginx/rutorrent.rpc2.error.log" 2021-4-18-2:0:0
"/config/log/nginx/error.log" 2021-4-15-2:0:0
"/config/log/nginx/rutorrent.rpc2.access.log" 2021-4-18-2:0:0
"/config/log/php/error.log" 2021-4-18-2:0:0
```

**Comment by saltydk** [comment]
I've poked @horjulf about it as it is his image. We'll see what he says.

**Comment by Sibicle** [comment]
nice! thanks for the swift reply 🙂
