### ISSUE TITLE
When you ssh into the server, bashrc doesn't get sourced

### ISSUE THREAD

**Issue by kungfoome** [Cloudbox/Cloudbox#463]
---

**Describe the problem**
If your shell is set to bash and you ssh into the server, bashrc does not get sourced and therefore all the options set in bashrc is not sourced

**Describe any solutions you think might work**
Add

``` shell
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
```
to  ~/.bash_profile

**Comment by saltydk** [comment]
I believe this is already implemented in develop.
