### ISSUE TITLE
Feature Request: Support for PlexSSO

### ISSUE THREAD

**Issue by sogeniusio** [Cloudbox/Cloudbox#464]
---

Instead of using just having Organizr as an SSO method, do we have any plans to add PlexSSO - [https://github.com/drkno/PlexSSOv2](https://github.com/drkno/PlexSSOv2) which uses Plex as the upstream authorization provider. This is designed to sit in front of various services and replace their authentication with a single unified login. Unlike other SSO providers such as Organizr it is stand-alone so isn't tied to any usage pattern or front-end.

**Comment by sogeniusio** [comment]
I tried implementing this myself, but wasn't able to find how to update the nginx.tmpl to add configs found here:

[https://github.com/drkno/PlexSSOv2/blob/master/nginx/example_sonarr.conf](https://github.com/drkno/PlexSSOv2/blob/master/nginx/example_sonarr.conf)

**Comment by saltydk** [comment]
We won't be implementing anything like this in the nginx branches. Can revisit this once traefik branch moves to develop.

**Comment by sogeniusio** [comment]
@saltydk thanks for considering. Are we able to use the develop_python branch right now to test traefik or should we just wait for it to move to develop? If not, when do you think we should expect to see it moved to develop?

**Comment by saltydk** [comment]
I'd wait since community isn't really done being updated for that branch yet. As for a timetable I'm afraid I cannot give one as I'm currently struggling with some health issues and work has stalled while I deal with that.

I run it personally but I can also updated roles as I need them so it isn't really a good benchmark in that regard.

**Comment by sogeniusio** [comment]
Ahh man. Sorry to hear that. Get well soon. Health is of paramount importance. I wish I had more experience in these technologies. This is such a great/useful project. I'd definitely be interested in contributing.

**Comment by owine** [comment]
Not planned
