### ISSUE TITLE
Using service-account-based remotes

### ISSUE THREAD

**Issue by vpatel9202** [Cloudbox/Cloudbox#468]
Is there a particular reason that CLoudbox initial setup/restore would not work using a service-account-based rclone remote rather than OAuth? From my understanding, the remote should look basically the same to cloudbox and whatever apps we're using and only rclone would really know that we're using a service account right?

**Comment by chazlarson** [comment]
If you're asking preemptively if you can use an SA-auth instead of the documented oauth workflow, the answer is sure, you can do that.
