### ISSUE TITLE
Feature Request: Support for Prowlarr, Readarr, Mylar, Swag

### ISSUE THREAD

**Issue by stitchemd** [Cloudbox/Cloudbox#472]
I wanted to make a couple suggestions tfor new integrations.

First would be for Prowlarr system as an option or replacement for Jacket and NZBHydra as it replaces both and direct links with most of the rr apps.

Also for Readarr as one of their newest additions to rr family of apps for books with Mylarr being for comics.

And then I saw you were working on an integration with trafiek also wanted to suggest Swag as it can now auto configure based on packages in the docker network and interfaces with both cloudflair and letsencrypt directly I'm not sure if it would ease any coding requirements at all but thought I'd at least make the suggestion.

Your project is amazing definitely appreciate all the hard work everyone has put into this.

**Comment by owine** [comment]
Prowlarr, Mylar and Readarr are in the [Community](https://github.com/Cloudbox/Community) repo.

I don't think simply moving from one nginx-based reverse proxy to another makes much sense.
