### ISSUE TITLE
Feature request: CloudFlare - add a setting to enable proxied

### ISSUE THREAD

**Issue by tinuva** [Cloudbox/Cloudbox#481]
---

**Describe the problem**
I have a firewall set up to only allow port 80/443 incoming connections from cloudflare ip ranges.
Currently I have to manually go and set each subdomain to proxied on the cloudflare website after running the ansible script

**Describe any solutions you think might work**
A setting in perhaps adv_settings to turn on proxied @ https://github.com/Cloudbox/Cloudbox/blob/master/roles/cloudflare-dns/tasks/main.yml#L33 with the default to "no" as it currently is.

**Comment by owine** [comment]
This is not planned - you would be better served removing Cloudflare credentials and just leaving your records intact with your Proxy preference.
