### ISSUE TITLE
update rutorrent to a newer image featuring v4

### ISSUE THREAD

**Issue by rmichelena** [Cloudbox/Cloudbox#482]
Cloudbox currently uses horjulf/rutorrent image, which uses rutorrent v 3.10 which is 2 years old.
(and actually there are many unsolved bugs on it)

According to rutorrent devs, that version is "ancient" and the current beta 4.0b2 is faster and more stable.
One docker image that incorporates that version was recommended by the ruTorrent team:
https://github.com/mondediefr/docker-rutorrent

Cloudbox should be upgraded to use that image or a similar one based on rutorrent v4 ...

**Comment by owine** [comment]
I’m closing this as it’s not likely something that will be done for a beta version. Different story once it goes stable.

**Comment by rmichelena** [comment]
On its way to 4.0 being stable real soon:
https://github.com/Novik/ruTorrent/releases

**Comment by rmichelena** [comment]
Hey guys, it's stable now
https://github.com/Novik/ruTorrent/releases
