### ISSUE TITLE
Cloudplow doesn't seem to be working anymore.

### ISSUE THREAD

**Issue by christcb03** [Cloudbox/Cloudbox#483]
**Describe the bug**
Cloudplow isn't moving files even when there is more data than the set limit to start a transfer. Also when I try to manually run it I get an error as shown below.

```
chris@cloudbox:~$ cloudplow upload
  File "/usr/local/bin/cloudplow", line 208
    notify.send(message=f"Upload suspension has expired for remote: {uploader_name}")
                                                                                   ^
SyntaxError: invalid syntax
chris@cloudbox:~$
```

**To Reproduce**
1. log into ssh session.
2. Type "cloudplow upload" <enter>
3. See error

**Expected behavior**
For cloudplow to run normally when space threshold is git and also when that command is run.

**Logs**
Not sure what logs to send but will send if asked for anything.

**System Information**

 - Cloudbox Version: Master (latest) I think
 - Operating System: Ubuntu Server 16.04.07 LTS
 - Linux Kernel: 4.15.0-142-generic

**Comment by owine** [comment]
Cloudplow now requires a newer version of Python which I do not believe is available on 16.04.

**Comment by christcb03** [comment]
So I have to upgrade the server to 18.04?

**Comment by owine** [comment]
> So I have to upgrade the server to 18.04?

Yes

**Comment by christcb03** [comment]
OK will try that, thank you
