### ISSUE TITLE
Some apps no longer work with nginx-proxy without exposing the apps ports to the WAN IP

### ISSUE THREAD

**Issue by edrock200** [Cloudbox/Cloudbox#484]
**Describe the bug**
I have a rather odd issue that started yesterday. Certain apps like sabnzbd, prowlarr and nzbhydra no longer work through the nginx-proxy. Others seem to work fine. In looking at the nginx logs, it says no live upstream provider. I then redeployed the apps exposing their respective ports to the WAN ip, and they started working, but this isn't something I've had to do before nor does it seem necessary for other apps such as sonarr. I was thinking it must be unique to my setup but I have a friend with a similar setup now seeing the same behavior.

I've confirmed the apps are deployed to the cloudbox network as well as nginx-proxy. I've tried restarting nginx-proxy and the app, redeploying the app, etc. but same issue resurfaces, specifically for these apps for some reason.

**To Reproduce**
deploy nzbhydra with "stock" setup, try to reach it via FQDN

**Expected behavior**
Connect to app

**System Information**

 - Cloudbox Version: Develop (latest)
 - Operating System: Ubuntu Server 18.04 LTS
 - Linux Kernel: 5.4

**Comment by owine** [comment]
Please update your repo(s) and re-run applicable tags. A fix was pushed a few minutes ago to expose the ports manually as the entries were removed from the upstream images.

**Comment by edrock200** [comment]
Thank you. But why would the ports need exposed at all if it was working using the internal cloudbox network between nginx-proxy and the container without ports being exposed before?

**Comment by owine** [comment]
You are confusing exposed ports (Docker terminology) with port binds/published ports. The ports are still not bound/published - that is unchanged. Until a couple of days ago, the upstream Docker images included an `EXPOSE` entry for the default web port. nginx-proxy is cranky if there is no port explicitly exposed, even though Cloudbox does not rely on it detecting the proper port.

**Comment by edrock200** [comment]
ahh thank you!
