### ISSUE TITLE
Error pulling image cr.hotio.dev/hotio/ombi:latest

### ISSUE THREAD

**Issue by ncrollo** [Cloudbox/Cloudbox#487]
**Describe the bug**
When running `sudo ansible-playbook cloudbox.yml --tags ombi` or any tag that calls _ombi_ the script fails with a 404 error.

**To Reproduce**
1. ssh to cloudbox install
2. run sudo ansible-playbook cloudbox.yml --tags ombi
3. See fatal error

**Expected behavior**
Expected script to fetch ombi 

**Screenshots**
N/A

**Logs**
N/A

**System Information**

 - Cloudbox Version: [1.4.5]
 - Operating System: 
 - Linux Kernel: 

**Additional context**
ombi is no longer listed as an available repo on https://hotio.dev/containers/

**Comment by owine** [comment]
The image was changed a few months ago so this suggests your repo is out of date.
