### ISSUE TITLE
update rutorrent to a newer image featuring v4

### ISSUE THREAD

**Issue by rmichelena** [Cloudbox/Cloudbox#488]
Cloudbox currently uses horjulf/rutorrent image, which uses rutorrent v 3.10 which is 2 years old.
(and actually there are many unsolved bugs on it)

v4.0 is now released (not beta) and devs says is faster and more stable.
https://github.com/Novik/ruTorrent/releases

One docker image that incorporates that version was recommended by the ruTorrent team:
https://github.com/mondediefr/docker-rutorrent

Cloudbox should be upgraded to use that image or a similar one based on rutorrent v4 ...

**Comment by owine** [comment]
We won't be migrating to a new image on Cloudbox being it is in maintenance mode. If the current image is updated to support v4 that Cloudbox will pick it up.

Saltbox, a fork of Cloudbox with active development, is looking at implementing when Docker image availability is bit broader.
