### ISSUE TITLE
hotio/suitarr Latest Image issue

### ISSUE THREAD

**Issue by sbcrumb** [Cloudbox/Cloudbox#49]
A day ago the image was reworked with
root/etc	Rework PORT configuration	a day ago
https://github.com/hotio/docker-suitarr/tree/master/root/etc
Since then using this image will cause the dockers to not start go unhealthy and to give a bad gateway from the proxy. Logs gives a no live upstream.  I tested this image is the issue by taking one I have on a working box creating a new one and uploaded it to docker to deploy to my box that I just installed yesterday that will not work. And the issues go away. Someone might want to look at his changes and how they affect the proxy config.

**Comment by l3uddz** [comment]
This is fixed in the develop branch. It will be in master shortly.
