### ISSUE TITLE
Installing cloudbox core fails on fuse3 dependency

### ISSUE THREAD

**Issue by edrock200** [Cloudbox/Cloudbox#491]
**Describe the bug**
When attempting "cb install core" with cb beta, it fails trying to install fuse3 on Ubuntu 18.04

**To Reproduce**
1. Clone CB beta repo
2. Run cb install preinstall
3. Run cb install core

**Expected behavior**
Install succeeds

**System Information**

 - Cloudbox Version:  Develop (latest)
 - Operating System: Ubuntu Server 18.04
 - Linux Kernel: [e.g. 5.15.0

**Additional context**
running apt install fuse3 yields package not found
editing ~/cloudbox/roles/system/tasks/subtasks/mounts.yml and changing fuse3 to fuse allows install to succeed, although unsure of side effects, if any.

**Comment by owine** [comment]
Reverted the change to fuse3, but #490 will probably be an issue and see my comments on a fix there.
