### ISSUE TITLE
Slack Invitation expired??

### ISSUE THREAD

**Issue by TheCreatorzOne** [Cloudbox/Cloudbox#50]
Well, yeah. The title says it all. The Slack invitation has expired, can we get a new one?

**Comment by l3uddz** [comment]
https://join.slack.com/t/cloud-box/shared_invite/enQtMjg0NTM4NTc2ODA1LTliOTdmMzM5YmNiZjU0ZDQxOWU0ZGQxN2E1MGE5NDIyM2VkZjE1MjQ1NmQ3ZjFhZTNhOGEzMmY1ZDViZTkyMzg
