### ISSUE TITLE
Radarr Issue

### ISSUE THREAD

**Issue by TheCreatorzOne** [Cloudbox/Cloudbox#51]
I'm getting a 502 Bad Gateway when trying to access radarr.myhostname.org
Am I missing something?

**Comment by l3uddz** [comment]
Please use the develop branch as this is fixed. I will merge with master in the coming days once some final touches are made.

**Comment by TheCreatorzOne** [comment]
Oh, I see. Since I just installed Cloudbox, how do I update to develop branch (Linux noob, sorry)?

**Comment by l3uddz** [comment]
make a copy of your settings.yml settings. then in the cloudbox folder `~/cloudbox`

```git fetch && git reset --hard origin/develop && git pull```

Then replace settings.yml values with the values from your configuration.

Should be good then.
