### ISSUE TITLE
Plex autoscan to quick on Feeder setup

### ISSUE THREAD

**Issue by Thomvh** [Cloudbox/Cloudbox#55]
Plex auto scan is too quick whilst using a feeder setup. The scan delay is only 180 seconds. After that, it tries for 10 minutes. But most uploads to Google aren't that quick.

**Comment by Thomvh** [comment]
Ah! Thanks for the tip. Maybe mention something of that in the wiki?

**Comment by desimaniac** [comment]
We're planning on automating some of that via Ansible.
