### ISSUE TITLE
Unable to find rclone on installation

### ISSUE THREAD

**Issue by neiliid** [Cloudbox/Cloudbox#58]
Hi,

I receive the following error when running the setup script, deploying as root:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/tmp/rclone-v1.38-linux-amd64/rclone'
fatal: [__server__]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/rclone-v1.38-linux-amd64/rclone'"}

I have checked the directory /tmp and the folder and file are there

root@server:/tmp/rclone-v1.38-linux-amd64# ls -la
total 17432
drwxrwxr-x  2 root root     4096 Jan 15 17:43 .
drwxrwxrwt 10 root root     4096 Jan 15 18:17 ..
-rwxrwxr-x  1 root root 16958816 Sep 30 14:23 rclone
-rw-rw-r--  1 root root   296086 Sep 30 14:21 rclone.1
-rw-rw-r--  1 root root   315539 Sep 30 14:21 README.html
-rw-rw-r--  1 root root   261497 Sep 30 14:21 README.txt

Any thoughts?

Thanks

N

**Comment by desimaniac** [comment]
In settings.yml, try changing the rclone version to 1.39.

**Comment by neiliid** [comment]
Thanks,

I did that, but no difference. I manually copied the files to the
appropriate location and # out the rclone reference in the cloudbox.yml. I
will create a standalone rclone installation from the existing cloudbox
files to step it through to see where the problem may lie.

**Comment by desimaniac** [comment]
The rclone installation task was redone. It should resolve this issue.
