### ISSUE TITLE
Different Image

### ISSUE THREAD

**Issue by RaymondSchnyder** [Cloudbox/Cloudbox#6]
Hi, i wanted to ask if its possible to create an alternative image which

- replaces radarr with couchpotato (Because radarr is not stable enough and buggy as hell)
- replaces nzbget with sabnzbd (Because i like sabnzbd more and it has more Features)

Is it possible to do this?

Could you lead me to a direction so i can fork it and do it myself?

Thank you :)

**Comment by kanenses** [comment]
Hello,

About that:
> replaces radarr with couchpotato (Because radarr is not stable enough and buggy as hell)
I do not agree, couchpotato are hard to wroking, bad setup and mostly radarr as amazing!
You can running container from portainer, and install 

Portainer: as install by default
Couchpotato: https://hub.docker.com/r/linuxserver/couchpotato/

> replaces nzbget with sabnzbd (Because i like sabnzbd more and it has more Features)
can have both of them :-)

**Comment by RaymondSchnyder** [comment]
Okay, i agree on your argument on couchpotato, as its a terrible piece of software which should be purged of the earth. But the problem with radarr i have currently:

Not all Mediafolders are named like this "Movie (2014)". Some are named, like "Movie" only, and Radarr NEEDS this year desperatly, so id would have to run filebot first to correctly name those folders/files to get them recognized by Radarr.

On your Second point, you stated i can have both of them... How did you mean that?
In the current setup, there is not automated install for sabnzbd right?
So id would have to install it for myself manually correct?

**Comment by l3uddz** [comment]
Currently there is no included installation of Couchpotato/Sabnzbd. Kanenses is correct though, these can be added manually via the command line using ```docker run``` or using the pre-installed Portainer. If you want to fork then you would need to be looking to create custom roles or replace the existing nzbget/radarr roles.  When I have some free time, I intend to create some example commands of how to add extra containers to the cloudbox setup, so will look to use sabnzbd and couchpotato as examples.

**Comment by desimaniac** [comment]
Like to mention that Movie (Year) is the Plex preferred naming scheme.

**Comment by l3uddz** [comment]
We are likely going to add some of these as extra apps that can be installed after a full/feeder/plex install. 

Already in the develop branch we have added Resilio Sync, Nextcloud and Ombi Beta.
