### ISSUE TITLE
Sickbear_mp4_automator

### ISSUE THREAD

**Issue by Chuntzu** [Cloudbox/Cloudbox#62]
Thank you for building this, it works great! I have everything up and running, but I am having trouble getting this postprocessing script to run with nzbget and sonar/radarr. I have had it working without using docker but realized that when these postprocessing scripts run they use the containers environment not the host. What would be the best way to go about adding the python dependances and possibly ffmpeg to nzbget/sonarr/radarr. Thank you for the help I appreciate it.

**Comment by desimaniac** [comment]
I made reply to that in the forums.
