### ISSUE TITLE
Media not appearing in plex

### ISSUE THREAD

**Issue by Organikk** [Cloudbox/Cloudbox#67]
Hi there,

I've read the FAQ's for Autoscan and also monitored all services and logs. Everything looks great with no warnings or errors. However nothing is populating in Plex automatically unless I run a manual scan.

Another odd things is that when I do run a manual library scan directly in Plex, it seems to hang. I have to refresh the browser but the media does show up.

This is all on a Vanilla unmodified version of Cloudbox that I installed about an hour ago and followed all configuration guides precisely. 

Any help is appreciated.

Thanks

**Comment by desimaniac** [comment]
You'll need to looks the the logs for Plex Autoscan and see why it's not running. Checkout the wiki page for "logs".

Then either come to the forums or join the discord chat.


On Feb 1, 2018, at 4:18 PM, Organikk <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

I've read the FAQ's for Autoscan and also monitored all services and logs. Everything looks great with no warnings or errors. However nothing is populating in Plex automatically unless I run a manual scan.

Any help is appreciated.

Thanks

**Comment by Organikk** [comment]
I would paste the logs but there is a lot of info in there I'd want to redact. I can say however that everything in the auto_scan log is an INFO event and not a warning or error. Here is a snippet:

```
2018-02-01 23:04:38,408 -     INFO -      PLEX [140517563864832]: Scan request is now being processed
 2018-02-01 23:04:38,425 -     INFO -      PLEX [140517563864832]: No 'Plex Media Scanner' processes were found.
 2018-02-01 23:04:38,425 -     INFO -      PLEX [140517563864832]: Starting Plex Scanner
 2018-02-01 23:04:38,692 -     INFO -      PLEX [140517563864832]: Finished scan!
 2018-02-01 23:04:38,706 -     INFO -      PLEX [140517563864832]: Removed '/data/Movies/<example>' from database
 2018-02-01 23:04:39,708 -     INFO -      PLEX [140517563864832]: There is 0 queued items remaining...
```

**Comment by desimaniac** [comment]
I suggested Discord since I thought it would be easier for you to share more detailed logs. 

Regarding, google drive.. please go thru the "UnionFS Cleaner" page. 

Regards to your redacted log file, I cant tell if the scan is working or not.

**Comment by Organikk** [comment]
It seems Autoscan is working now fairly consistently now. Not sure if that is from me enabling 'Partial Library Scans' in Plex or if it just decided to work. Google drive is also working as expected once I hit the criteria for upload.

I appreciate your help troubleshooting that.

**Comment by desimaniac** [comment]
You don't need "partial library scans" for it to work.
